### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Kianosh107** [SimVascular/SimVascular#1015]
I am encountering an issue in Sim Vascular. Specifically, upon drawing paths and attempting to select “Torn on realizing,” I am presented with an unexpected image. What could be the cause of this problem?
<img width="1661" alt="Screenshot 2023-02-22 at 12 08 13" src="https://user-images.githubusercontent.com/118909024/220605039-8320aeeb-18f7-4827-a505-40f326f26952.png">

**Comment by ktbolt** [comment]
@Kianosh107 Please post this question in  the SimVascular forum https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=188&pluginname=phpBB so other users can see it.
