### ISSUE TITLE
Add writing svFSIplus XML files to the svFSI Tool

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/SimVascular#1016]
Add writing svFSIplus XML files to the svFSI Tool.

**Comment by ktbolt** [comment]
I've added an `XML Format` radio button to select writing the solver commands input file in XML format used by svFSIplus.

<img width="494" alt="Screen Shot 2023-07-27 at 8 22 05 PM" src="https://github.com/SimVascular/SimVascular/assets/23109458/52472688-b2d6-4267-b715-49525bd46218">

**Comment by alisonmarsden** [comment]
﻿Fantastic!

From: Dave Parker ***@***.***>
Date: Thursday, July 27, 2023 at 8:25 PM
To: SimVascular/SimVascular ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [SimVascular/SimVascular] Add writing svFSIplus XML files to the svFSI Tool (Issue #1016)

I've added an XML Format radio button to select writing the solver commands input file in XML format used by svFSIplus.
[Screen Shot 2023-07-27 at 8 22 05 PM]<https://user-images.githubusercontent.com/23109458/256714434-52472688-b2d6-4267-b715-49525bd46218.png>

**Comment by ktbolt** [comment]
I've added an `Sv4GuiXmlWriter` class in `SimVascular/Code/Source/sv4gui/Modules/svFSI` to write an XML file using `tinyxml2`. XML elements are added with data stored in an `sv4guisvFSIJob* job` object
```
auto general = doc.NewElement("GeneralSimulationParameters");
auto num_spatial_dims = add_child(doc, general, "Number_of_spatial_dimensions");
num_spatial_dims->SetText(job->nsd);
```
The XML file looks good for the `GeneralSimulationParameters`.

**Comment by ktbolt** [comment]
I've added the remaining solver commands and tested using the `WCB_Demo_Project` on MacOS and Ubuntu 20. I then ran  svFSIplus with the XML file and it worked fine.

**Comment by ktbolt** [comment]
Merged into `master`.
