### ISSUE TITLE
Simulation file generated by SimVascular for the 0D solver not working with the C++ 0D solver

### ISSUE THREAD

**Issue by AndreaZanoni** [SimVascular/SimVascular#1019]
The keyword "BloodVesselJunction" for the junction type should be replaced by "NORMAL_JUNCTION" in the simulation file generated by SimVascular for the 0D solver. Also, the file extension of the simulation file should be ".json" instead of ".in".

**Comment by mrp089** [comment]
We removed `internal_junction` from `svZeroDSolver` in https://github.com/SimVascular/svZeroDSolver/pull/78. However, it's still written for junctions with one inlet and one outlet:
https://github.com/SimVascular/SimVascular/blob/bb559fc4f42c34d464fca03ada23fc27a07bf359/Python/site-packages/sv_rom_simulation/io_0d.py#L88

All junctions should be `NORMAL_JUNCTION`.
