### ISSUE TITLE
Mouse tracking is incorrect on some macs

### ISSUE THREAD

**Issue by alexkaiser** [SimVascular/SimVascular#1026]
**Describe the bug**
When clicking on images the click response does not correctly track the mouse cursor. 

**To Reproduce**
1. Click on a location in an image in the GUI. 
2. The image crosshairs go somewhere other than the click location. 

**Expected behavior**
The crosshairs should move to the spot that was clicked. 

**Desktop (please complete the following information):**
 - OS: Macbook Pro M1 Max, Ventura 13.3.1
 - SimVascular Version 2022-07-20
 - Medical Image Filetype DICOM 

**Additional context**
This problem does not occur when I open SV with the laptop closed and it attached to an external monitor. Opening SV with the laptop screen open and the monitor does reproduce the problem.

**Comment by ktbolt** [comment]
@alexkaiser This is a known issue with a workaround. 

See https://github.com/SimVascular/SimVascular/issues/980
