### ISSUE TITLE
Boundary Mesh Extruded in Wrong Direction

### ISSUE THREAD

**Issue by natalia-rubio** [SimVascular/SimVascular#1048]
**Describe the bug**
Boundary layer mesh is extruded out of the vessel, instead of into the vessel, creating a weird/unusable mesh.  Occurs with geometries constructed along the X direction, but not along the Y direction.  You cannot see the outwards extruded points in Paraview unless you take a cross-sectional slice/clip.

**To Reproduce**
These geometries were generated with the code in [this folder of my repo](https://github.com/natalia-rubio/vessel_pressure_differentials/tree/main/util/geometry_generation).  To change the axis along which the vessel is built, swap the sin and cos in lines 14 and 15 of path_planning.py

**Screenshots**
Working:
![image](https://github.com/SimVascular/SimVascular/assets/68125155/f7040881-c93e-41f7-8902-ace4ebbfe65f)
Not Working:
![image](https://github.com/SimVascular/SimVascular/assets/68125155/85a2f75c-0d44-45e5-b1f5-6ce1430e1a5e)

Actual files linked [here](https://drive.google.com/drive/folders/1QDYcIsVjSPCxhP22brt--Xw8BD-8TJZ1?usp=sharing)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - SimVascular Version 5.23.2029

**Comment by natalia-rubio** [comment]
Sorry my hyperlink didn't work before.  The repo folder containing path_planning.py is now linked in the original comment.

**Comment by ktbolt** [comment]
@natalia-rubio How do you use the Python scripts in your repo to generate a mesh?

**Comment by natalia-rubio** [comment]
I generate a dictionary which contains the geometric parameters defining the vessel in `write_vessel_params.py`.  Then in `construct_geometries.py` I call functions to do the path planning, segmentation, modeling, and meshing based on the geometry defined in the geometric parameter dictionary.  The functions I call from `construct_geometries.py `are defined in `path_planning.py`, `radius_planning.py`, `segmentation.py`, and `modeling_and_meshing.py`.

**Comment by ktbolt** [comment]
@natalia-rubio The Python code is looking for some hard-coded directories like `data/synthetic_vessels/vessel_params_dict` and such.

Do you have a script that you use to setup the directory structure needed and run this Python code?

**Comment by natalia-rubio** [comment]
Yes, this is in `write_vessel_params.py`

**Comment by ktbolt** [comment]
I finally got the scripts to work, needed to manually create directories and `sys.path.append()` statements.

After changing `path_planning.py` I ran
```
construct_geometries.py straight mesh_convergence
```
and examined `data/synthetic_vessels/straight/mesh_convergence/s_3/mesh-complete/mesh-complete.mesh.vtu`, looked good to me, boundary elements inside
<img width="391" alt="Screen Shot 2024-01-29 at 2 23 19 PM" src="https://github.com/SimVascular/SimVascular/assets/23109458/91a41cd7-d12f-4250-84af-2271658f0f08">

Is this the correct way to run the scripts?

**Comment by natalia-rubio** [comment]
Okay, yes I could add some more lines to create directories.  Which `sys.path.append()` statements did you need to add?

Did you try looking at an x-normal slice/clip of the vessel, somewhere in the middle, not at the caps?  That was the only way I could really see the extra points

**Comment by ktbolt** [comment]
The first mesh refinement iteration in `data/synthetic_vessels/straight/mesh_convergence/s_0/` is correct but later iterations are not. Note that all of the elements in the incorrect meshes are valid, have positive Jacobians, but the surface extraction is not working correctly, perhaps a face orientation issue.

I was able to mesh a cylinder model along [1,0,0] correctly using a script in `SimVascular-Tests/new-api-tests/meshing`.

I thinking something is going wrong when refining the mesh, looking into that now.

**Comment by ktbolt** [comment]
The bad boundary layer elements are being created in the VMTK function `vtkvmtkBoundaryLayerGenerator`.  The problem depends on  the `sv.meshing.TetGenOptions` `global_edge_size`  value. If it is too small then bad elements are generated, not sure what the size dependency is all about though.

@natalia-rubio I will close this Issue since it is not impacting your work.
