### ISSUE TITLE
Fill Holes w. IDs using Python API

### ISSUE THREAD

**Issue by fkong7** [SimVascular/SimVascular#1051]
**Is your feature request related to a problem? Please describe.**
There is currently no Python API function to fill holes in a surface mesh while also assigning the cell data array "ModelFaceIDs" to the newly created faces. This function was previously available but has been removed due to issues mentioned in #749. 
```
capped_cylinder = sv.vmtk.cap_with_ids(surface=model_polydata, fill_id=0, increment_id=True)
```
Currently, only `sv.vmtk.cap(surface, use_center)` is available but this function does not add the array "ModelFaceIDs" to the returned vtkPolyData object. 

**Describe the solution you'd like**
It would be great to have a working Python API function to automate the "Fill Holes with IDs" functionality in the GUI. 

**Describe alternatives you've considered**
One workaround proposed in #749 was to use the `compute_boundary_faces` function to recompute boundary faces by surface normals. However, for cardiac geometries without much surface normal differences between the valve face and the ventricle walls, this alternative doesn't work well.

```
modeler = sv.modeling.Modeler(sv.modeling.Kernel.POLYDATA)
capped_polydata = sv.vmtk.cap(surface=polydata, use_center=False)
capped_model = sv.modeling.PolyData()
capped_model.set_surface(surface=capped_polydata)
face_ids = capped_model.compute_boundary_faces(angle=60.0)
```

**Comment by ktbolt** [comment]
@fkong7 Upload a file of a surface mesh you would like to have the holes filled for.

**Comment by ktbolt** [comment]
I've tested `sv.vmtk.cap()` on 

<img width="542" alt="Screen Shot 2024-03-14 at 3 24 58 PM" src="https://github.com/SimVascular/SimVascular/assets/23109458/114d1f25-01c9-4c9c-ab6b-42a9a4b5cb15">

and get a surface with `face IDs: [1, 2, 3, 4, 5, 6]` and a `ModelFaceID` array
<img width="434" alt="Screen Shot 2024-03-14 at 3 27 47 PM" src="https://github.com/SimVascular/SimVascular/assets/23109458/0d43887c-24f9-44c9-821a-6a912440d0d8">

SimVascular produces the same result.

**Comment by fkong7** [comment]
@ktbolt sv.vmtk.cap() worked for me. Thanks Dave!
