### ISSUE TITLE
Using lots of memory when generating input files

### ISSUE THREAD

**Issue by riioze** [SimVascular/SimVascular#1068]
**Describe the bug**
When using the python console to write several different ROM simulation input files simvascular starts to use lots of memory even if the python script deletes the variable between each input file generation.
It leads to simvascular being very slow once it reaches 1G of memory usage

**To Reproduce**
1. Use a python script to create several input files using loops 
2. After around 200 input files generated simvascular uses around 1G of memory and becomes very slow

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - SimVascular Version [2023-05]

Is it possible to force simvascular to empty its memory through python script or to import sv outside of simvascular python console ?

**Comment by ktbolt** [comment]
@riioze It might be that the SV Python interface is not freeing memory. 

It is not clear what exactly your script doing so please include it here.

**Comment by riioze** [comment]
Hi,
Thank you for your quick answer.
 
My goal here is to create input files for a lot of different rom simulation using a range of parameters and put them in files with this architecture : 
 - M1 M2 ect corresponding to a base centerline file
     - S1 S2 ect corresponding to the centerline file with variations on lengths and radius of the arteries
         -  F1 F2 ect corresponding to different flow files for the inlet face
             -  E1 E2 ect corresponding to different values of the k3 parameter
                 - R1 R2 ect corresponding to different resistence value for the outlet faces
              
The input directory has this architecture
- centerlines
    - H1 H2 H3 each containg multiple centerline files
        - PA-0.vtp PA-1.vtp ect corresponding to different variations for lengths and radius of the arteries of a same base centerline file
- flows
    - flow-0.flow flow-1.flow
- resistances
    - resistance1.csv resistance2.csv ect each containing different combinations of resistances for the outlet faces 


import csv
import os
from pathlib import Path
import sv

#Set the paths to your data, input, and output directories
script_path = Path(os.path.realpath('/path/to/files'))
#directory with the different range of parameters
input_dir = script_path / 'input'
#directory where the input files for rom sim are generated
output_dir = script_path / 'output'


#Ensure the output directory exists
output_dir.mkdir(exist_ok=True)

#List centerline directories (H1, H2, H3, ...)
centerline_base_path = input_dir / "centerlines"
centerline_dirs = sorted([d for d in centerline_base_path.iterdir() if d.is_dir()])

#Path to the resistances directory
resistances_dir = input_dir / 'resistances'

#List flow files
flow_path = input_dir / "flows"
flow_files = sorted(os.listdir(str(flow_path)))
#Create a ROM simulation object
rom_simulation = sv.simulation.ROM()

#Create ROM simulation parameters
params = sv.simulation.ROMParameters()

#Mesh parameters (modify as needed)
mesh_params = params.MeshParameters()
mesh_params.num_branch_segments = 1

#Model parameters (modify as needed)
model_params = params.ModelParameters()
model_params.name = "1D_solver"
model_params.inlet_face_names = ['inflow']
model_params.outlet_face_names = ['o1', 'o2', 'o3', 'o4', 'o5', 'o6', 'o7', 'o8', 'o9', 'o10', 'o11', 'o12', 'o13', 'o14', 'o15', 'o16']

#Fluid properties (modify as needed)
fluid_props = params.FluidProperties()
fluid_props.viscosity = 0.04

#Solution parameters (modify as needed)
solution_params = params.Solution()
solution_params.time_step = 0.001
solution_params.num_time_steps = 4000 # 10000
solution_params.save_frequency = 10

#Wall properties (modify as needed)
print("Set wall properties ...")
mat = params.WallProperties
material = params.WallProperties.OlufsenMaterial()
material.k1 = 0
material.k2 = 0
material.exponent = 1
material.pressure = 0.0
k3_values = [600000,1200000,1800000] # Values for material.k3

m_idx = 1
centerline_dir = centerline_dirs[m_idx-1]
m_dir = output_dir / "M{}".format(m_idx)
m_dir.mkdir(exist_ok=True)
print(centerline_dir)
#Select the appropriate resistances CSV file based on m_idx
resistances_file =str( resistances_dir / "resistances{}.csv".format(m_idx))

#Load data from the CSV file
resistances = []
with open(resistances_file, 'r', newline='') as file:
    reader = csv.reader(file)
    next(reader)  # Skip header row
    for row in reader:
        resistance_row = {}
        for idx, cell in enumerate(row):
            resistance_row['R{}'.format(idx+1)] = cell
        resistances.append(resistance_row)

#List only .vtp files in the current directory (PA-0, PA-1, PA-2, ...)
centerline_files = sorted([f for f in os.listdir(str(centerline_dir)) if f.endswith('.vtp')])

#Set the model parameters' centerlines file name
for i,centerline_file in enumerate(centerline_files,start=1):

    base_centerline_dir = m_dir / "S{}".format(i)
    base_centerline_dir.mkdir(exist_ok=True)

    # Iterate over flow files
    for j, flow_file in enumerate(flow_files, start=1):
        base_flow_dir = base_centerline_dir / "F{}".format(j)
        base_flow_dir.mkdir(exist_ok=True)
        
        # Iterate over k3 values
        for k3_idx, k3 in enumerate(k3_values, start=1):
            
            base_elasticity_dir = base_flow_dir / "E{}".format(k3_idx)
            base_elasticity_dir.mkdir(exist_ok=True)

            # Iterate over resistances combinations
            for k, row in enumerate(resistances, start=1):
                
                




                # Generate output file path for the specific resistance set and k3 value
                specific_output_dir = base_elasticity_dir / "R{}".format(k)
                specific_output_dir.mkdir(exist_ok=True)
                

                # Boundary conditions (modify as needed)
                bcs = params.BoundaryConditions()
                bcs.add_velocities(face_name='inflow', file_name=str(flow_path / "flow-{}.flow".format(j-1)))
                
                material.k3 = k3

                model_params.centerlines_file_name = str(centerline_dir / centerline_file)
                # Add resistances
                for idx in range(1, 17):  # Assuming there are 16 outlet faces
                    resistance_value = float(row['R{}'.format(idx)])
                    bcs.add_resistance(face_name='o{}'.format(idx), resistance=resistance_value)

                rom_simulation.write_input_file(
                    model_order=1,
                    model=model_params,
                    mesh=mesh_params,
                    fluid=fluid_props,
                    material=material,
                    boundary_conditions=bcs,
                    solution=solution_params,
                    directory=str(specific_output_dir)
                )

I tried to delete rom_simulation after each call of write_input_files and use gc but it didn't change anything to the memory problem

**Comment by ktbolt** [comment]
@riioze The Python script appears to use only Python classes defined in `sv.simulation.ROM` and does not use any of the SV Python API implemented in C++. The memory used by the script should be garbage collected. 

You are running the script in the SV Python Console? Try running it from the command line.

**Comment by riioze** [comment]
I always execute the code in the text editor as I don't see how to do for loops in the console.
I also tried to call gc.collect() but I didn't see any change. I'll try to execute it on a windows laptop to see if it changes something.

**Comment by ktbolt** [comment]
@riioze The line `rom_simulation = sv.simulation.ROM()` does in fact call the SV Python API to create a `rom_simulation` object, I forgot how all of this worked, sorry!

I ran a test calling `rom_simulation.write_input_file()` for 100,000 times and do see SV memory increasing from 60MB to around 200MB.  So there might be some CPython objects that are not being released. There might be also something going on in the 1D mesh generation Python code. But this does not explain the memory usage you are seeing.

If you send me  the data that I can use to test your Python script I'll investigate further.

**Comment by riioze** [comment]
[input_files_generation.zip](https://github.com/user-attachments/files/17288746/input_files_generation.zip)
Here is the folder,
You just have to change the path in the python script and open it in simvascular.

**Comment by ktbolt** [comment]
@riioze I ran your script and data to generate 240 input files. On MacOS Ventura M2 it used about 150MB of memory.

Let me create an Ubuntu 22 VM and test there.

**Comment by riioze** [comment]
I just tried on a windows 10 computer and I had the same problem. with simvascular using almost 1G of ram and slowing a lot.
Maybe am I doing something wrong when lauching the python code ?

**Comment by ktbolt** [comment]
@riioze I run the Python script using
```
/usr/local/sv/2023-03-27/simvascular --python -- input_generation.py
```
To be clear, `VIRT` memory is around 1G when SV starts and `RES` memory grows to 270MB as the script runs. I created about 1000 1D solver input files with only about a 20MB increate in memory usage so I don't think memory usage is the problem. How much memory does your system have?

How many 1D solver input files are you thinking to create? Maybe you could try creating them in stages.

**Comment by riioze** [comment]
I see, I was using the python editor in the gui to execute the python file. Executing from, cmd I don't have memory problems.
Thank you very much for your time and help.
Now that the probleme is fixed for me can I close the issue ?

**Comment by ktbolt** [comment]
@riioze I'm glad things are working! 

Please close the issue.
