### ISSUE TITLE
It's fail when I compilied SimVascular 2.0 using CMake

### ISSUE THREAD

**Issue by janeyuhui** [SimVascular/SimVascular#109]
Hi,

It's my first time  to compile this project, and I fail.
I had built VTK and ITK, follow this link: http://simvascular.github.io/docsCompile.html
Then i built SimVascular.

When i push the button "Configure", it's error, It show that

> SimVascular Version: simvascular 2.0.21008
> Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
> Note: explicitly adding TCL_LIBRARY_PATH to link path.
> PKG TCL found!
> PKG VTK found!
> PKG ITK found!

SuperBuild - First pass
SuperBuild - First pass - done
Install timestamp: 161008100917
Note: explicitly adding TCL_LIBRARY_PATH to link path.

Libraries:
    Source/Common/Globals
    Source/Common/Utils
    Source/Common/Repository
    Source/ImageProcessing
    Source/Common/Geometry
    Source/Legacy/LevelSet
    Source/Model/SolidModel
    Source/PostProcessing
    Source/Mesh/MeshObject
    Source/Model/PolyDataSolidModel
    Source/Mesh/TetGenMeshObject
    ThirdParty/vmtk
    Source/Segmentation/ITK
Executables
    Source/UI
**CMake Error at Source/UI/CMakeLists.txt:4 (get_filename_component):
  get_filename_component called with incorrect number of arguments**

Generating simvascular scripts. Dev name: mysim, install name:  simvascular
simvascular
Configuring incomplete, errors occurred!
See also "E:/workspace/SimVascular-master/bin/CMakeFiles/CMakeOutput.log".
See also "E:/workspace/SimVascular-master/bin/CMakeFiles/CMakeError.log".

I donot know where I am error, why i fail. I cannot fix this. please help me. THANK YOU.

**Comment by updega2** [comment]
Hi!

Sorry for the slow response! What system/compilers are you using? 

We have made some pretty large changes to SimVascular's build system lately, and it is very possible that there are some still some outstanding issues that need to be fixed for all systems/compilers. Your approach to building SimVascular is correct for previous versions of SimVascular. If you are going to do this, I would suggest cloning a version of the repository from before June of this year.

I will post here when things seemed to be more streamlined and clean with documentation and hopefully you will be able to build a newer versions of the source. 

Additionally, if you are just looking to use the code, we have binaries posted here: https://simtk.org/frs/?group_id=188
This way, you will not have to compile the code.

**Comment by osmsc** [comment]
The latest git master (as of 2017-06-18) now successfully builds on Linux, MacOS, and Windows as long as you are using a supported compiler & platform.  Please try again.
