### ISSUE TITLE
SimVascular / VTK compilation explanation.

### ISSUE THREAD

**Issue by ellach** [SimVascular/SimVascular#150]
I cloned VTK 6.0 as described [http://simvascular.github.io/docsCompile.html](compile guide).
You suggest to compile/configure it with gcc 4.6 (as far as I understand gcc compilers for windows mainly come with MinGW BUT you don't support it ). So I used the default visual studio compiler (14 2015 win64) as advised in VTK guide.
As a result i receive a lot of errors during configuration for instance:
![vtkerror](https://cloud.githubusercontent.com/assets/24588427/21966428/cbfb4b70-db27-11e6-935e-5ee11027c288.PNG)
After configuration is finished or (kinda finished):
[CMakeError.txt](https://github.com/SimVascular/SimVascular/files/706929/CMakeError.txt)
I turn on TK and TCL BUT configure produce the following error:
`Could NOT find Tclsh (missing:  TCL_TCLSH) 
Could NOT find TCL (missing:  TCL_LIBRARY TCL_INCLUDE_PATH) 
Could NOT find TCLTK (missing:  TCL_LIBRARY TCL_INCLUDE_PATH TK_LIBRARY TK_INCLUDE_PATH) 
Could NOT find TK (missing:  TK_LIBRARY TK_INCLUDE_PATH) 
CMake Error at CMake/vtkWrapTcl.cmake:205 (MESSAGE):
  Tcl was not found.  Install the Tcl development package (see http://tcl.tk
  or ActiveState Tcl) and set the appropriate variables (TCL_INCLUDE_PATH,
  TCL_LIBRARY, TCL_TCLSH) or disable VTK_WRAP_TCL.
Call Stack (most recent call first):
  CMake/vtkTclWrapping.cmake:4 (include)
  CMake/vtkWrapping.cmake:10 (include)
  CMake/vtkModuleMacros.cmake:7 (include)
  CMakeLists.txt:18 (include)`

I am not sure which TCL version do I need, its not specified in your documentation.(and Simvascular will not compile without VTK so I'm kinda lost .......)
Can you please help me to compile Simvascular with all necessary dependencies (maybe there is more accurate explanation regarding how to compile the whole project).

**Comment by updega2** [comment]
Thanks for the post. We are actually currently in the process of making large changes to the source code and the build system. The documentation for the build system is out of date. We hope to clean up major changes in the next few months and post updated build documentation. 

We have prebuilt binaries of the software if you are just looking to use the software: https://simtk.org/frs/?group_id=188

**Comment by mikeRozen** [comment]
Thanks for quick reply.
Currently we are looking for open source and the compilation process is really stuck.
Few months is too much time to wait.
Maybe you can at least post the basic configurations/(build versions)  how it runs on your systems  so I will try to reproduce it, with some minor/basic explanation.
Really appreciate your help.

**Comment by osmsc** [comment]
Unfortunately, the website is out of date regarding the build instructions.  If you are building on Windows, you can't use the MSVC 2015 compiler.  Only the MSVC 2013 compiler is supported due to the versions of the external libraries we are using.  Until we get a chance to update the build documentation, I would suggest looking at the scripts in:

BuildWithMake/

  quick-build-linux.sh
  quick-build-macosx.sh
  quick-build-windows.sh

These scripts download pre-compiled external libraries for the required open source packages.  They also indicate the version number for the software.  Some of the code requires patches that have been applied per the scripts in the "Externals" top-level directory.

To run the script on Windows, you need to install Cygwin (including wget and tclsh packages).  If you want to try and build with CMake, there are some sample scripts in "Externals/TestWithCMake".

Hope that helps!

**Comment by ellach** [comment]
Thanks a lot for your help.
We still have some problems running the makeFile 
[errorLog.txt](https://github.com/SimVascular/SimVascular/files/714026/errorLog.txt)
Its look like we also need a QT ? Can you please tell me which package exactly we need in Cygwin.<br>
We also had problem with _tclsh_ by installing the last version 8.6.4 directly on windows we get the following 

> error:/bin/sh: /usr/bin/tclsh: No such file or directory  

So we installed 8.5 version via Cygwin. I am not sure but running _make_ only search Cygwin paths (maybe I am wrong). I hope it will not cause any problems in future. (That what may happen for QT, _make_ will not recognize if we installed not via Cygwin)

Another thing that confuse us is how to work on that project. Do you use VS as IDE? Should we create a new project(with specific configuration?) and add the source code OR there is already a project which we can use?

**Comment by mikeRozen** [comment]
Hi Guys,
Maybe you can update us on the previous question from _**ellach**_?

**Comment by ellach** [comment]
Hi **osmsc ,updega2,**,
We download _qt-opensource-windows-x86-msvc2013_64_opengl-5.4.2.exe_ from [https://download.qt.io/archive/qt/5.4/5.4.2/](QT5.4.2).<br> 
According to the version specified in _qt-5.4.x64_cygwin.mk_
`QT_TOP_DIR	= C:/OpenSource/Qt/Qt5.4.2/5.4/msvc2013_64_opengl`<br>
But this version wont launch on widows 10 x 64 (Home , Entrprise edition, we turned off security configuration that could prevent the install but no luck).
Will it be compatible with another QT version that you know, if yes do we need to update only QT_TOP_DIR for it to work?
Did you try to run it on win 10 or should we downgrade to another windows version?
Can you please assist?

**Comment by osmsc** [comment]
I do all my development on Windows 10.  The installer for Qt 5.4.2 will install on Windows 10.   Be sure to save it to a local disk (i.e. not a network drive or share) and then run the executable.  If you're firewall (or Windows) is blocking it, you should be able to click on a small link to "install anyway" like any other Windows installer.

In make, you can also specify:

SV_USE_QT = 0
SV_USE_QT_GUI = 0

in the "global_overrides.mk" file.

**Comment by ellach** [comment]
Thanks for your help **osmsc**,
Its seems that we have some internal compilation errors.
Qt was installed after windows updates (strange).
I did change the .bat file of cygwin by adding _CALL "%VS120COMNTOOLS%\vsvars32.bat"_
But now we receive some compilation errors :<br>
`** [../../../../BuildWithMake/targetlib.mk:113: ../../../../BuildWithMake/Lib/x64_cygwin/msvc-12.5-ifort/lib_simvascular_qtgui_module_common.dll] Error 88
make[2]: *** [../../../../BuildWithMake/MakeHelpers/rules.x64_cygwin.mk:41: obj/x64_cygwin/msvc-12.5-ifort/svSegmentationLegacyIO.obj] Error 2
make[2]: *** [../../../../BuildWithMake/MakeHelpers/rules.x64_cygwin.mk:41: obj/x64_cygwin/msvc-12.5-ifort/svResliceSlider.obj] Error 2
make[2]: *** [../../../../BuildWithMake/MakeHelpers/rules.x64_cygwin.mk:41: obj/x64_cygwin/msvc-12.5-ifort/svPathLegacyIO.obj] Error 2
make[2]: *** [../../../../BuildWithMake/MakeHelpers/rules.x64_cygwin.mk:41: obj/x64_cygwin/msvc-12.5-ifort/svModelLegacyIO.obj] Error 2
make[2]: *** [../../../../BuildWithMake/MakeHelpers/rules.x64_cygwin.mk:41: obj/x64_cygwin/msvc-12.5-ifort/svMeshLegacyIO.obj] Error 2                                                                                                                                                                                                           
make[2]: *** [../../../../BuildWithMake/targetlib.mk:113: ../../../../BuildWithMake/Lib/x64_cygwin/msvc-12.5-ifort/lib_simvascular_qtgui_module_simulation.dll] Error 157
make[2]: *** [../../../../BuildWithMake/MakeHelpers/rules.x64_cygwin.mk:41: obj/x64_cygwin/msvc-12.5-ifort/svProjectManager.obj] Error 2
make[1]: *** [Makefile:64: shared] Error 2
make[2]: *** [../../../../../../BuildWithMake/MakeHelpers/rules.x64_cygwin.mk:41: obj/x64_cygwin/msvc-12.5-ifort/svProjectDataNodesPluginActivator.obj] Error 2
make[2]: *** [../../../../../../BuildWithMake/MakeHelpers/rules.x64_cygwin.mk:41: obj/x64_cygwin/msvc-12.5-ifort/svProjectManagerPluginActivator.obj] Error 2
make[2]: *** [../../../../../../BuildWithMake/MakeHelpers/rules.x64_cygwin.mk:41: obj/x64_cygwin/msvc-12.5-ifort/svModelCreate.obj] Error 2
make[2]: *** [../../../../../../BuildWithMake/MakeHelpers/rules.x64_cygwin.mk:41: obj/x64_cygwin/msvc-12.5-ifort/svPathCreate.obj] Error 2
make[2]: *** [../../../../../../BuildWithMake/MakeHelpers/rules.x64_cygwin.mk:41: obj/x64_cygwin/msvc-12.5-ifort/svContourGroupCreate.obj] Error 2
make[2]: *** [../../../../../../BuildWithMake/MakeHelpers/rules.x64_cygwin.mk:41: obj/x64_cygwin/msvc-12.5-ifort/svMeshCreate.obj] Error 2
make[2]: *** [../../../../../../BuildWithMake/MakeHelpers/rules.x64_cygwin.mk:41: obj/x64_cygwin/msvc-12.5-ifort/svSimJobCreate.obj] Error 2
make[2]: *** [../../../../../../BuildWithMake/MakeHelpers/rules.x64_cygwin.mk:41: obj/x64_cygwin/msvc-12.5-ifort/svFileCreateProjectAction.obj] Error 2
make[1]: *** [Makefile:71: shared] Error 2
make: *** [Makefile:244: shared-build] Error 2`

[errorLog.txt](https://github.com/SimVascular/SimVascular/files/740521/errorLog.txt)

Do we need to specify also the fortran compiler ??? (just guessing)
(but the fortran compiler doesnt located with all the msvc compilers )
Can you suggest what to do?

**Comment by mikeRozen** [comment]
**osmsc**,
Can you at least explain us the error or why it may happen?
Unfortunately we have no bod else to ask.
Thanks.

**Comment by ktbolt** [comment]
Old issue.
