### ISSUE TITLE
Can`t open project file in IDE 

### ISSUE THREAD

**Issue by ellach** [SimVascular/SimVascular#218]
Hi,
I succeeded to compile SimVascular on Ubuntu 16.4, now I want to open the code and work on it, can you advice what work space/IDE Do I need to create project file (if yes how we do it, how it should be defined ) ?
Thanks,

**Comment by ellach** [comment]
P.S
I  trying  to open it with Eclipse (kepler c/c++), but it seems that I need to define some variables in IDE.
Should I open it like "Makefile project with existing code"  or  like c++ project?

**Comment by osmsc** [comment]
We don't explicitly support any IDE.  I believe most of the team develops using command-line tools and emacs.  I don't personally have experience with Eclipse, so I can't provide any advice.
