### ISSUE TITLE
CMAKE_INSTALL_PREFIX doesn't propagate when building using Code/CMakeLists.txt

### ISSUE THREAD

**Issue by osmsc** [SimVascular/SimVascular#236]
When you build SV using CMake from the "Code" directory, the CMAKE_INSTALL_PREFIX doesn't propagate into the "SimVascular-build" directory.

**Comment by updega2** [comment]
This should already be changed in the current master:

https://github.com/SimVascular/SimVascular/blob/4c3da24ca81968c227a8715580aa02f10e8c701f/CMakeLists.txt#L170
