### ISSUE TITLE
CMAKE_INSTALL_PREFIX can't have spaces on Windows

### ISSUE THREAD

**Issue by osmsc** [SimVascular/SimVascular#237]
Doing an "INSTALL" build causes errors if the path contains spaces on Windows.  The default install path:

"C:/Program Files/SV" therefore breaks the install.  The options are to fix all of the cmake installs (potentially including tcl, etc.) OR override the default install path to something like:

C:/svinstall
C:/sv

etc.

**Comment by updega2** [comment]
Is this definitely a spaces issue? Googling around it looked like this could potentially be a permissions thing as well.

**Comment by ktbolt** [comment]
Old issue.
