### ISSUE TITLE
Convert Results taking a really long time

### ISSUE THREAD

**Issue by DMLON** [SimVascular/SimVascular#374]
Hello, there seems to be a problem when converting many results (700), the files are created after some time, but simvascular keeps loading as if it's doing something. I can access the files and view them in paraview thou.

**Comment by DMLON** [comment]
Hello,
The program is stuck in a "not responding" status for a long time after all of the vtu and vtp files are created, in this example i converted 1000 steps.
In the image i'm showing the program not responding and the folder with the last step and the average_result.vtp file at the end. 
What is the program doing? Why is it taking so long to come back to a responsive status?
It takes like 5 minutes to process the 1000 files and 2 hours to let me interact with the program again.
![break](https://user-images.githubusercontent.com/29444416/49828298-48877e00-fd6a-11e8-8958-282c70e7c808.png)

Thank you.

**Comment by ktbolt** [comment]
Thanks for the update and screen shot, now I understand the problem.

What OS are you running on? 

I'll have a look at the code to see what could possibly be taking two hours to complete.

Dave

**Comment by DMLON** [comment]
Hello, Here are my system specs
![image](https://user-images.githubusercontent.com/29444416/49891700-e5f3b800-fe25-11e8-87a0-2cb177e0e431.png)

**Comment by ktbolt** [comment]
I don't see anything in the code that could account for the delay you are seeing. The results files are converted and then flow quantities at the caps are calculated and written. 

How big is your mesh? If it took only five minutes to convert then it must be small, it takes about 30 minutes to convert a 100 step simulation for the Demo problem.

Try converting using a single file be selecting the **As Single File** checkbox and see what happens. This should be fast and also use a lot less memory.

Dave
