### ISSUE TITLE
Writing simulation files in Simulation tool fails with boundary layer meshing.

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/SimVascular#377]
**Describe the bug**
The Simulation tool fails to create data files for simulation when the model is meshed with a boundary layer. The program svpre seg faults when trying to process .vtp files for the inflow boundary because there is no 'GlobalNodeID' scalar data.

**To Reproduce**
1. Mesh a bound with a boundary layer
2. In the Simulation tool click on 'Create Data Files for Simulation'
3. A window pops up with the message 'Failed to finish creating data files'

**Expected behavior**
The simulation input files should be created for a mesh with a boundary layer.

**Desktop (please complete the following information):**
 - OS: all
 - SimVascular Version  2018-11

**Comment by ktbolt** [comment]
The inflow surface .vtp files are different with and without a boundary layer. Without a boundary layer there is an entry in the .vtp file like this

          <PointData Scalars="GlobalNodeID">
        <DataArray type="Int32" Name="GlobalNodeID" format="appended" RangeMin="956"                  RangeMax="2647"                 offset="0"                   />
      </PointData>

With a boundary layer there is an entry like this

      <PointData>
        <DataArray type="Int32" Name="GlobalNodeID" format="appended" RangeMin="1911"                 RangeMax="7633"                 offset="0"                   />
      </PointData>


I'm not sure why there is this difference.

In the svpre code there is a call to a VTK method GetScalars() with no tag to get node IDs. Adding a "GlobalNodeID" tag to the GetScalars() fixes the problem finding scalar data for this.

**Comment by ktbolt** [comment]
I made the changes to svSolver.

**Comment by rohanshad** [comment]
Meshes with boundary layers still lead to segmentation faults for svpre on the latest Mac OS binaries:

/usr/local/sv/svsolver/2017-08-14/bin/../svpre: line 56: 78493 Segmentation fault: 11  $SV_HOME/bin/svpre $*

**Comment by ktbolt** [comment]
@rohanshad The latest svSolver version is 2019.01.19. It seems that you are still using the previous version of svSolver (2017-08-14). svSolver is has its own installer, separate from SimVascular.

**Comment by rohanshad** [comment]
My bad, thanks!
