### ISSUE TITLE
Node ordering in boundary layer elements is wrong

### ISSUE THREAD

**Issue by kirkbhansen** [SimVascular/SimVascular#389]
**Describe the bug**
Node ordering in boundary layer elements is wrong. (This is separate from issue #377; I worked around that by manually adding 'Scalars="GlobalNodeID"' in the .vtp file.)

**To Reproduce**
1. Create mesh with BL elements.
2. Open .vtu in ParaView.
3. Tet volume in mesh quality filter is negative for BL elements.
4. Also causes simulation to blow up, was fixed when I changed nodes to proper order.

**Desktop (please complete the following information):**
 - OS: macOS Sierra
 - SimVascular Version 2018-12-03

**Comment by ktbolt** [comment]
@kirkbhansen I was able to reproduce this problem for the cylinder demo project, I will have a look.
<img width="903" alt="screen shot 2018-12-21 at 10 57 38 am" src="https://user-images.githubusercontent.com/23109458/50358830-7bbad180-050f-11e9-99e3-bde3464f539d.png">

**Comment by ktbolt** [comment]
I wrote several vtk utilities to investigate this. The boundary layer mesh is initially created using **VMTKUtils_BoundaryLayerMesh()** which generates a wedge element volume mesh with correct element node ordering. This wedge-based mesh is then later converted into a tet mesh using **vtkvmtkUnstructuredGridTetraFilter()**. The node ordering for the tets in the mesh is wrong though and generates negative Jacobians.

**Comment by ktbolt** [comment]
I've added the function **VMTKUtils_ReorderTetElements** to **sv_vmtk_utils.cxx** to reorder tetrahedral elements in an extruded inward boundary layer mesh. I've tested on several models and it seems to work. 
![cylinder-volume-quality](https://user-images.githubusercontent.com/23109458/51001344-9c5dc200-14e4-11e9-8da0-5b954197e235.png)

**Comment by ktbolt** [comment]
The new code has been integrated into the Simvascular repository, will be in a new Simvascular release this week.
