### ISSUE TITLE
svPre solver fails when trying to create job files for meshes with boundary layer meshing.

### ISSUE THREAD

**Issue by rohanshad** [SimVascular/SimVascular#395]
**Describe the bug**
When trying to save simulation files using a mesh with boundary layer meshing, the svpresolver crashes with the error code:

/usr/local/sv/svsolver/2017-08-14/bin/../svpre: line 56: 63912 Segmentation fault: 11  $SV_HOME/bin/svpre $*

For the same settings, the simulation files are created correctly by svpresolver when using a mesh without boundary layers.

**To Reproduce**
1. Mesh model with boundary layer meshing selected
2. Set up simulation in the SV Simulation panel
3. Scroll down to "Create files and Run Simulation"
4. A popup is displayed that says "Data files have been created"
5. Click "Show Details"
6. See error code as listed above.

**Expected behavior**
The  bct.dat, numstart.dat, restart.0.1 files should be created in the simulation directory, with a a list of successful steps printed in the popup on clicking "Show Details"

**Desktop:**
 - Mac OS Mojave
 - SimVascular Version [e.g. 2018-11-25]

**Comment by ktbolt** [comment]
@rohanshad This is a known bug (see #377) and has been fixed in the GitHub source repository for svSolver. We will be releasing a new version of svSolver within the next couple of weeks.
