### ISSUE TITLE
The Segmentations Plugin contour group reslice window size limit is too small

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/SimVascular#399]
Suhaas was trying to create a contour group using the **Segmentations Plugin** for a scaled image (units originally in microns). The reslice window (red rectangle in the main window) size limit was set to 100 which was too small to include the anatomical feature he was trying to segment.

<img width="1629" alt="screen shot 2019-01-23 at 3 18 02 pm" src="https://user-images.githubusercontent.com/23109458/51643912-1188b880-1f23-11e9-880c-6e1ace57d3c3.png">

**Comment by ktbolt** [comment]
The widget setting the reslice window size was not defined in any of the plugin Qt .ui files. Instead it is defined programmatically in Code/Source/sv4gui/Modules/QtWidgets/sv4gui_ResliceSlider.cxx, the widget limits set in a method call. This is the only widget defined like this.

I added some comments and used variables to set the widget values. tested and works. I built a Linux installer for Suhass for the short term.

**Comment by osmsc** [comment]
@ktbolt - is this code ready to integrate into master?  Did you create "Options" for the user to set?  This is what we did in the old GUI.

**Comment by ktbolt** [comment]
@osmsc The change was to increase the max range in the slice sample window slider, I will integrate the change today.

**Comment by ktbolt** [comment]
Pushed fix to master.
