### ISSUE TITLE
Exporting .step and .iges not compatible with Solidworks or SpaceClaim

### ISSUE THREAD

**Issue by swnlia001** [SimVascular/SimVascular#400]
**Describe the bug**
My model of a coarctation is segmented okay however creating a polydata model crashes SimVascular ("simvascular-bin.exe has stopped responding"). Generating an OpenCASCADE model works and can be converted to polydata fine. Exporting the OpenCASCADE model to .iges or .step does not generate a complete (or it is corrupted) model. This can be seen if opened in Solidworks or Spaceclaim.

**To Reproduce**
1. Import DICOM as vti and scale 0.001
2. Change window size to see image and segment
3. Use thresholding and manual segmentation
4. Create PolyData model with default settings (crashes here usually)
5. Create OpenCASCADE with default settings and convert to PolyData
6. Smooth Poly Data model and export as stl (export model -> save as *.stl)
7. Export OpenCASCADE (export model -> save as *.iges)

**Expected behavior**
The .iges file is generated but is a small file (approx. 360kB). Opening it in Solidworks or SpaceClaim shows and incomplete and irregular model. .step export is even worse. Re-importing the .iges or .step files into the SimVascular case seems to give a model that looks okay however it is still needed in SpaceClaim.

**Screenshots**
.STEP File
![image](https://user-images.githubusercontent.com/46969157/51671178-042a0780-1fd1-11e9-96f0-89f60476b652.png)

.STL File
![modelstl](https://user-images.githubusercontent.com/46969157/51671207-1310ba00-1fd1-11e9-882c-fd28d33c2c56.PNG)

.IGES File
![modeliges](https://user-images.githubusercontent.com/46969157/51671210-1310ba00-1fd1-11e9-8cb9-92b36fea0017.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SimVascular Version 2018-11-26
 - Medical Image Filetype DICOM (scaled to mm on import (0.001))

**Additional context**
Is the scaling an issue?

I have done this before on the version released with the WCB Workshop in Dublin and the models exported fine. In that case I hadn't scaled the images and was working with a different data set. I have tried using a previous version of SimVascular although the problem persists. 

Thanks for the help.

**Comment by ktbolt** [comment]
Hi @swnlia001, 

This might be a scaling issue, not sure about that though. We have fixed a major bug when saving image data in vti format and reading it back in, scaling was wrong for the vti data. Please try downloading the new SimVascular release and see if that solves your problem. 

Cheers,
Dave

**Comment by swnlia001** [comment]
Hi Dave

Thank you for the suggestion. I will try the updated version and not scaling the image and refer back to you.

Kind regards
Liam

**Comment by osmsc** [comment]
Hi @swnlia001,

To be clear, the default units in DICOM is mm.  You are scaling your data to be in meters.  While this is the default in most CAD packages, SimVascular is used to dealing with data in mm and cm and likely has hardcoded tolerances in various points of the code that take this into account.

I would highly recommend either building models in mm (scaling 1.0) or cm (scaling 0.1).  We almost always build models in cm now.  It leads to more intuitive units in the simulation results, and avoids a Parasolid issue.  Just realize that "meters" is actually cm if you import into SolidWorks.  

Parasolid-based solid modeling packages have a bounding box limitation of 600 x 600 x 600 m.  This can create issues if you import full body CT scans and build the model in mm.  This shouldn't happen in cm.

Nathan

**Comment by swnlia001** [comment]
Hi Dave and Nathan

Just to let you know that not scaling the images worked out well. Thanks for the help.

Liam

**Comment by ktbolt** [comment]
@swnlia001 Good to hear! 

I will make a note to myself tp add documentation to the SimVascular web page describing the potential problems associated with scaling.
