### ISSUE TITLE
Defaults to resetting view when creating new paths

### ISSUE THREAD

**Issue by melodydong** [SimVascular/SimVascular#404]
**Describe the bug**
When you find a new vessel to model by scrolling through the 3-plane views and click "create new path", SimVascular automatically resets the 3 axial views to the default view and the user has to scroll through the axial views again to find that new vessel.  This is frustrating when trying to find daughter vessels to a parent vessel and have to keep rescrolling through the slices to find the same daughter vessel you want to create a path for.

**To Reproduce**
1. Go to Paths. Scroll through the image slices
2. Click on "Create New Path"
3. SimVascular resets the image window.

**Expected behavior**
When you click "create new path", the image should not reset and should remain in the same cross-hair view as before clicking "create new path".

**Desktop (please complete the following information):**
 - OS: Windows 10 (but also for all versions)
 - SimVascular Version [e.g. 2018-07-05]
 - Medical Image Filetype [e.g. DICOM, MHA, ...]

**Comment by ktbolt** [comment]
The function **sv4guiPathEdit::OnSelectionChanged()** is called when selecting a path node from the data manager. 

The Image node (**baseData**) is then reset using:

       mitk::RenderingManager::GetInstance()->InitializeViews(
                    baseData->GetTimeGeometry(), mitk::RenderingManager::REQUEST_UPDATE_ALL, true );
        mitk::RenderingManager::GetInstance()->RequestUpdateAll();

I commented out this code and the image is no longer reset when selecting a path node.  I don't know why the image was being reset, no comments describing why this was done, but it seems that it was just a design decision. I will scrutinize a bit more ...

**Comment by ktbolt** [comment]
@melodydong I have fixed this, will check in the fix soon and figure out how to build a new Windows installer for you.

**Comment by ktbolt** [comment]
@melodydong I've pushed the fix to the main SimVascular repo. @osmsc please review and build a new Windows installer for Melody.
