### ISSUE TITLE
Add some additional functions for Python Path API

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/SimVascular#425]
I am writing some scripts to better understand the Python interface. One script I am writing computes the distance between two control points on a path. 

The Path Python API does not have a function to get control points so I will add that.

**Comment by ktbolt** [comment]
@fkong7 I was trying to use the **Repository.Exists()** function in a script to test if a repository has already been added but it did does not work as one would expect in an if-statement, testing if it returned true or false 

    if Repository.Exists('path1'):
        print('true')

I see that  **Repos_ExistsCmd()** in **sv_repos_init_py.cxx** returns a string rather than an int. Shouldn't this return an int?

**Comment by fkong7** [comment]
@ktbolt I agree that this should be changed to return an int. I think most of the Python functions return strings now, same as what TCL functions do: some of the Python functions return "success", same as TCL functions. I think these should be improved to follow Python style. This should be an easy fix; I can look into that.

**Comment by ktbolt** [comment]
@fkong7 Sounds good, thanks!

**Comment by ktbolt** [comment]
I am finished with this for now. Created a pull request.
