### ISSUE TITLE
Long error message window

### ISSUE THREAD

**Issue by melodydong** [SimVascular/SimVascular#430]
Super long error messages do not have scroll button and prevent user from seeing entire message and clicking ok.

**To Reproduce**
For large models, errors with faces contribute to long messages

**Expected behavior**
Add scrolling in the error windows

**Screenshots**
![image](https://user-images.githubusercontent.com/16911253/54398428-34a82c80-4677-11e9-99a8-4dbee021694e.png)

**Desktop (please complete the following information):**
Windows and Linux

**Comment by melodydong** [comment]
![Screenshot from 2019-03-15 10-59-27](https://user-images.githubusercontent.com/16911253/54452120-96b57000-4711-11e9-958a-3688309d4804.png)

**Comment by ktbolt** [comment]
@melodydong I've added a scrolling message box for the display of these errors.
![face-disp-error](https://user-images.githubusercontent.com/23109458/54459857-1bf65000-4725-11e9-827d-ff9957dcfb68.png)

**Comment by ktbolt** [comment]
Finished with this, did a pull request.
