### ISSUE TITLE
Setting Data Node names with non-alphanumberic characters is allowed

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/SimVascular#470]
**Describe the bug**
When creating a new Data Node (e.g. Paths -> Create Path) the user is prompted to input a name. SV accepts a name containing any character. This causes problems when writing files using the Data Node name. 

**To Reproduce**
Create a Segmentation Data Node name with a space, e.g. **L Branch**. Generate a model for this segmentation, it will have face names with a space. Later during mesh files used in a simulation will have names containing spaces. The simulation to fail trying to process the .svpre file  because it contains file names with spaces (fails to parse).

**Desktop (please complete the following information):**
 - OS: All
 

**Additional context**

**Comment by ktbolt** [comment]
I've added checks for offensive Data Node names for all of the plugins. When an invalid name is given a popup is displayed

<img width="722" alt="error-msg" src="https://user-images.githubusercontent.com/23109458/58450841-ac59f500-80c5-11e9-999a-62ac63ef01d1.png">

A Data Node name

1) Starts with a letter, number or an underscore (_)
2) Has no spaces.
3) Can use underscores (_) or single dot (.), dash (-) as separators. 
4) Does not start or end with a dot or dash.

**Comment by melodydong** [comment]
When creating simulation files and converting results, if the folder with all of the restart files has a path name with spaces in it, SimVascular has trouble locating files and it will fail to create simulations files and convert results.  There is no pop up error when this occurs.

**Comment by ktbolt** [comment]
@melodydong The simulation folder name is the Job Name supplied by the user. The new SV will not allow Job Names with spaces. 

But the user could create a folder with spaces in it to hold the results from a simulation on a cluster. Is this the case you are talking about?

**Comment by melodydong** [comment]
Yes, when they create a folder to hold their project and results folder, it causes an error.

**Comment by ktbolt** [comment]
@melodydong OK, this is a different problem, I will open an Issue for this.
