### ISSUE TITLE
BUG: sv4gui/Modules/Simulation1d/python needs to move to Python/site-packages

### ISSUE THREAD

**Issue by osmsc** [SimVascular/SimVascular#484]
The python code for the 1-D solver should in the directory:

Python/site-packages/

in something like:

Python/site-packages/sv_1d_simulation

**Comment by osmsc** [comment]
@ktbolt - can you move the 1-D python code.  It should be in a library that we can import via:

import sv_1d_simulation

or something like this.

**Comment by ktbolt** [comment]
@osmsc I will do that today.

**Comment by osmsc** [comment]
@ktbolt - thanks.  You can delete the older copy of your files that I put in site-packages/sv_1d_simulation.  Be sure to add copyright notices to the files once you move them.  I got stuck trying to update the functions in C++ to call the python code in the 1-D plugin.

**Comment by ktbolt** [comment]
I've moved the Python code over to the SV Python/sites-packages and tested on MacOS and Ubuntu, looks good.

**Comment by osmsc** [comment]
works on Windows, closing bug.
