### ISSUE TITLE
Contour geometry area incorrect

### ISSUE THREAD

**Issue by eleighschwarz** [SimVascular/SimVascular#496]
**Describe the bug**
The area reported by the contour geometry info area (bottom bar after clicking on segmentation) is significantly incorrect, noticed when resizing segmentations to create artificial stenosis and realizing the area was actually much smaller than the reported value just by comparing relative volumes, and then confirmed when I used a python program to calculate contour areas.

**To Reproduce**
1. Create contour
2. Click on contour number to pull up contour geometry info on bottom bar

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.5
 - SimVascular Version 2019.05.02
 - Medical Image Filetype DICOM

**Comment by ktbolt** [comment]
The contour center is used to calculate the contour area but it was not being calculated when the contour group is read when a project is opened, the center just had random values.

I have fixed this by calculating and setting the contour center when contour groups are read in.
