### ISSUE TITLE
BUG: multi-segmentation using ML can create duplicate group names that overwrite existing groups

### ISSUE THREAD

**Issue by osmsc** [SimVascular/SimVascular#502]
**Describe the bug**
If you have existing group names the same as the paths (e.g. aorta), when you create the machine learning groups it creates new groups of exactly the same name.  When these groups are saved, the original groups are lost when you reload the project (since the files are overwritten).

**To Reproduce**
1. Launch SV
2. Load the demo project
3. Launch the 2-D segmentation plugin
3. Click on the multi-path segmentation
4. Segment all the paths
5. Save the project and reload

**Expected behavior**
The multi-path segmentation gui needs to create non-existing group names or refuse to run.

**Screenshots**
![duplicate-group-names](https://user-images.githubusercontent.com/13802982/58777041-3bad4f80-8581-11e9-9c0a-15d34b7acbd6.JPG)

**Desktop:**
 - OS: Windows 10
 - SimVascular Version: 2019-06-02

**Comment by gmaher** [comment]
Fixing this now.
