### ISSUE TITLE
Clicking on Lofting Parameters button crashes when no contour group selected.

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/SimVascular#521]
When you start SV a **SV 2D Segmentation** tool panel can be displayed that is not associated with any contour group. When you click on the [b]Lofting Parameters[/b] button SV crashes.

**Desktop:**
 - OS: All
 - SimVascular Version: latest

**Comment by ktbolt** [comment]
The crash occurs because no contour group has been created (**m_ContourGroup** is null) but widgets are active and their callbacks are executed and try to use **m_ContourGroup**.

All other tool panels widgets are grayed out and disabled if the panel has no data. This is done using
```
m_Parent->setEnabled(false)
```
@gmaher I see that you have commented out these statements in the ***2D Segmentation** plugin with the **warnings if no segmentation selected** commit. Why did you need to remove these guys?

**Comment by gmaher** [comment]
Oh yes, that was necessary to allow the multi-path segmentation to be used when no segmentations have been made yet. Seems like this is an unintended side-effect.

I can look into fixing this.

**Comment by ktbolt** [comment]
@gmaher One fix is to put checks for m_ContourGroup null in the widgets callbacks, not very pretty but it would do the trick.

 It is much better to gray out the wigets. This issue came from a user who thought the tool was active and clicked on the [b]Lofting Parameters[/b] button.

**Comment by ktbolt** [comment]
Fixed this by disabling the widgets in the Single Path tab.
