### ISSUE TITLE
The 1D Simulation Tool panel does not resize.

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/SimVascular#541]
The widgets in the 1D Simulation Tool panel do not resize.  This has been verified for Windows and MacOS.

The widgets do resize correctly using the **2019.02** externals.

**Comment by osmsc** [comment]
@ktbolt - so I guess this means it's a Qt 5.11 vs. Qt 5.6 issue.  I'm surprised, but then again, I'm not surprised.

**Comment by ktbolt** [comment]
@osmsc Correct: a Qt 5.11 vs. Qt 5.6 issue. I adjusted the widget layouts and widgets now resize OK on MacOS.
