### ISSUE TITLE
Removal of data manager object through python

### ISSUE THREAD

**Issue by TobiasJacobson** [SimVascular/SimVascular#561]
**Is your feature request related to a problem? Please describe.**
I'm running into the issue that when I run a python script through the Python Console in SimVascular, I can only run in once before it gives me an error of 'some item already exists'. My solution to this has been quitting and restarting simVascular every time I run a script more than once, which has been a huge pain

**Describe the solution you'd like**
I'd like the ability to remove items from the data manager through python scripts, much like we already can with clearing the repo. But instead apply it to the data manager. 

**Describe alternatives you've considered**
I've considered just removing it manually item by item in the GUI, though effective, its not as efficient as through a script. 

**Additional context**
I have personally emailed Fanwei about this functionality and she said she would address it. I'm submitting this as per request of Alison to have it documented.

**Comment by ktbolt** [comment]
@TobiasJacobson I just recently noticed this lack of functionality too, needs to be fixed.

**Comment by fkong7** [comment]
I just added this function and a data node can now be removed with GUI.RemoveDataNode('childName', ‘folderName').
