### ISSUE TITLE
Add creating 1D solver mesh segments based on vessel radii 

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/SimVascular#578]
1D solver mesh segments are currently created based on vessel bifurcations and do not account for changes in vessel radii. 

Add functionality to the SV **sv_1d_simulation** Python package to create mesh segments based on vessel radii.

**Comment by mrp089** [comment]
Related to pull request #624.

To connect the new 1d model creation plugin, add three parameters to the GUI:

- min. number of sub-segments per vessel branch (int)
- spacing of sub-segments (float)
- option for adaptive spacing based on the change in cross-sectional area (bool)

Add options between "Element size" input and "Calculate Centerlines" button.

![1d_box](https://user-images.githubusercontent.com/51269309/70956834-752f3f00-2029-11ea-84cf-689e2565edf3.png)

**Comment by mrp089** [comment]
1D segments can be created based on vessel radii (introduced in #655) by activating the ```Adaptive meshing``` option in #657
