### ISSUE TITLE
Shifted GlobalNodeID and GlobalElementID for multi-domain boundary layer meshes

### ISSUE THREAD

**Issue by vvedula22** [SimVascular/SimVascular#579]
**Describe the bug**
When creating multi-domain meshes using boundary-layer extrusion approach, typically done for creating wall meshes for FSI simulations, the GlobalNodeID and GlobalElementID data arrays do not start from 1 but are shifted by the total number of nodes and elements in the previous domains.

As a result, svFSI produces 'Out of Bounds' when trying to access mesh coordinates and connectivity using global indices. On some compilers, instead of detecting out of bounds and memory leaks, it will produce projection errors.

**To Reproduce**
1. Download the cylinder demo data

2. Create a wall mesh using boundary layer extrusion
    https://simvascular.github.io/docssvFSI.html#wall_mesh

3. You will see that the global indices are all shifted.

**Desktop (please complete the following information):**
All platforms.

**Comment by ktbolt** [comment]
@vvedula22 are you going to fix this or shall I have a look?

**Comment by vvedula22** [comment]
I think it is better to do this at SimVascular end, which I don't have much experience with, rather than svFSI end.

**Comment by ktbolt** [comment]
OK, I'll have at it. Note that the boundary layer code is buggy, I've already fixed a couple of bugs in it. There are also several issues open for it.

**Comment by vvedula22** [comment]
UPDATE: I just noticed that merely resetting the node and element indices of the solid domain will not work. The GlobalNodeIDs of the fluid mesh are also messed up after boundary layer extrusion. The GlobalNodeID pointer of the faces (vtp) do not correspond to the node IDs of the mesh (vtu) but to the GlobalNodeID of the mesh.

**Comment by updega2** [comment]
@vvedula22 Can you explain that last comment again? This part specifically: "The GlobalNodeID pointer of the faces (vtp) do not correspond to the node IDs of the mesh (vtu) but to the GlobalNodeID of the mesh."

**Comment by updega2** [comment]
@vvedula22 As far as the actual issue brought up in this ticket, this is expected behavior. When developing this code, I consulted with Justin for export requirements. Justin stated that svFSI renumbers the points and uses physical coordinates, so the node ids would not need to start back at 1 for the other domains and the shifted node/element ids would work well.

**Comment by vvedula22** [comment]
Thanks Adam @updega2 for looking into this issue. 

> @vvedula22 Can you explain that last comment again? This part specifically: "The GlobalNodeID pointer of the faces (vtp) do not correspond to the node IDs of the mesh (vtu) but to the GlobalNodeID of the mesh."

I think the main issue is that the GlobalNodeID of a face does not correspond to the mesh node ID. I have attached two snapshots - first one shows the settings I used to create a solid mesh via boundary layer extrusion; second one shows the issue I am talking about. 

In the second, I have selected a set of points on the fluid interface (top-left panel) and also selected the corresponding nodes on the mesh (bottom-left panel). While the physical coordinates of these two are exact and their GlobalNodeIDs match (see the right panels), the GlobalNodeID of the face (top-right panel) does not match with the vtkOriginalPointID of the mesh (bottom-left). 

I also don't understand why we need a GlobalNodeID for the mesh, but that is a different issue.

**Comment by vvedula22** [comment]
> @vvedula22 As far as the actual issue brought up in this ticket, this is expected behavior. When developing this code, I consulted with Justin for export requirements. Justin stated that svFSI renumbers the points and uses physical coordinates, so the node ids would not need to start back at 1 for the other domains and the shifted node/element ids would work well.

I see. But I guess that is not entirely true. svFSI doesn't read/store face coordinates at all. It only reads mesh coordinates and face's GlobalNodeID and GlobalElementID, using which it will extract the position coordinates of the face. For multiple meshes, it will stack the meshes' coordinates and elements and accordingly displaces the GlobalNodeIDs and GlobalElementIDs. Now that these indices are already displaced during mesh generation, svFSI further displaces and fails during projection step due to array out of bounds.

**Comment by updega2** [comment]
@vvedula22 What version of the software are you using? I just tested using a version from July 2018 and received the same vtkOriginalPointIds. However, I'm not sure vtkOriginalPointIds is required to stay the same anyway. SimVascular uses GlobalNodeID, and that was the requirement here as well. 

I also noticed that there is an "Allow Multiple Regions" option that wasn't available in the old version. What does that do? Does that have any affect on this?

**Comment by ktbolt** [comment]
I've started (finally) looking in to this. 

I guess everyone knows this already but the nodal coordinates on the interface between the extruded solid mesh and the inner (fluid) mesh are duplicated (green spheres in the image below).

<img width="1151" alt="Screen Shot 2019-09-25 at 2 23 42 PM" src="https://user-images.githubusercontent.com/23109458/65640932-56785980-dfa0-11e9-8a22-6a1910a48f2b.png">

**Comment by ktbolt** [comment]
@vvedula22 The **Convert Boundary Layer to New Region/Domain** option adds a DataArray named **ModelRegionID** to the mesh .vtu file. svFSI does not read that field so how does it determine the solid and fluid meshes? 

Not using the **Convert Boundary Layer to New Region/Domain** option generates a mesh without duplicate nodes.

**Comment by vvedula22** [comment]
@updega2 you are right. vtkOriginalPointIds are the same but that is not the required feature. It is the GlobalNodeID that should be the same. Dave @ktbolt said he made some changes to the boundary later code later. I don't know what 'Allow Multiple Regions' does but it didn't have any effect on the present result.

**Comment by vvedula22** [comment]
@ktbolt I think the option **Convert Boundary Layer to New Region/Domain** allows to create two different domains - fluid domain and a solid domain that are distinguished using the ModelRegionID. Domains are used in svFSI to set properties such as density, elasticity modulus, viscosity, body forces, etc. svFSI can read the domain data from file but is not usually done. Instead, the user sets a domain/region ID for fluid mesh and solid mesh in the input file as the IDs are usually constant across the entire solid/fluid mesh. However, if you have variable wall properties, then a domain/region ID is set locally in the solid mesh. svFSI then reads a vtu/dat file to set a domain ID for each element in the mesh.

If you don't set this option, I think the interface nodes are then duplicated - one set for the fluid side and the other set for the solid side.

**Comment by ktbolt** [comment]
**Allow Multiple Regions** allows the meshing of disconnected geometry.

**Comment by ktbolt** [comment]
@vvedula22 The **Convert Boundary Layer to New Region/Domain** option duplicates nodes on the interface and sets two region IDs in the **ModelRegionID** array. Here's the results of processing the vtu file for the cylinder problem with the option set

```
Read volume mesh: ../extrude-convert.vtu
  Number of points: 5508
  Number of cells: 23750
Number of point data arrays: 1
Point data array names: 
  1: GlobalNodeID type: 6
Number of cell data arrays: 2
Cell data array names: 
  1: GlobalElementID type: 6
  2: ModelRegionID type: 6
---------- Checking node IDs ----------
Number of node IDs: 5508
Number of coordinates: 5508
Number of duplicate coordinates: 1030
```

And here's the vtu file with the option not set

```
Read volume mesh: extrude-no-convert.vtu
  Number of points: 4478
  Number of cells: 23750
Number of point data arrays: 1
Point data array names:
  1: GlobalNodeID type: 6
Number of cell data arrays: 2
Cell data array names:
  1: ModelRegionID type: 6
  2: GlobalElementID type: 6
---------- Checking node IDs ----------
Number of node IDs: 4478
Number of coordinates: 4478
Number of duplicate coordinates: 0
```

**Comment by ktbolt** [comment]
@vvedula22 I can fix the SV code to removed the duplicate nodes and renumber the element connectivity. Would this solve the problem?

**Comment by vvedula22** [comment]
@ktbolt I don't think that would fix the issue. In fact, we need that option to be able to create a separate fluid and solid domains. If we don't set the **Convert Boundary Layer to New Region/Domain** option, then all we get is a single domain and we cannot do FSI.

**Comment by ktbolt** [comment]
I've fixed the problem with duplicate nodes. I need to now test to see if exporting the separate fluid and solid meshes does the right thing.

**Comment by ktbolt** [comment]
I think this is working correctly now. I wrote out an extruded boundary layer mesh, then read it in using a Python script and created two meshes using region IDs. Both meshes shared global node IDs for nodes on their shared interface (red markers).

<img width="1257" alt="Screen Shot 2019-11-21 at 9 41 19 PM" src="https://user-images.githubusercontent.com/23109458/69400929-4b902b80-0ca8-11ea-80ca-277e34742720.png">

**Comment by ktbolt** [comment]
I've simplified and cleaned up the code, added comments and have done some more testing, looks good.
