### ISSUE TITLE
Crash once selecting "After" adding mode from SV Path Planing tool.

### ISSUE THREAD

**Issue by hmuucsd** [SimVascular/SimVascular#591]
**Describe the bug**
When I was working on the demo project, SimVascular (SV) quit automatically when I was adding the first path point. I had one model already made, and I was trying to build models based on renal arteries. 

**To Reproduce**
1. Make a aorta model on the Demo project. Stop at the "Solid Modeling (PolyData)" in the Modeling Guide of SimVascular site.
2. Create a new path and double click to open the SV Path Planning tab.
3. Select "After" in the Adding Mode
4. Choose a point on the image and click "Add"
5. SV crashes.

**Desktop (please complete the following information):**
 - macOS Mojave, 10.14.1
 - SimVascular Version: 2019.08.09 (MITK 2018.4.2; VTK 8.1.1; ITK 4.13.2; Qt 5.11.3)
 - Medical Image Filetype: .xmi and .vti. The Demo Project on SV website.

**Comment by ktbolt** [comment]
Fixed, added check for empty control point list.
