### ISSUE TITLE
svFSI GUI plugin needs to be updated

### ISSUE THREAD

**Issue by vvedula22** [SimVascular/SimVascular#592]
Just adding it here so we can keep track of it.

The GUI plugin for svFSI needs to be updated with the most recent version of svFSI

**Comment by ktbolt** [comment]
@vvedula22 It seems that the format of the svFSI solver input .txt file has changed, for example
```
Mesh file path (vtu):    ->  Mesh file path:
Face file path (vtp):     ->  Face file path:
...
Viscosity: 0.04   ->  Viscosity: constant { Value:0.4 }
```
Could you please document the changes here so I can update SV svFSI tool to write out the correct format.

**Comment by vvedula22** [comment]
Yes, there are many changes to the code related to input commands. Changes include not only for the fluid physics but other physics as well. Can we go over this tomorrow, if you time, and we could figure out how best to address this.

**Comment by ktbolt** [comment]
@vvedula22 I'm unable to discuss today. If you can describe where the new parameters should be in the GUI (e.g. under the **Physics** panel) and how they should be written to the solver input file (e.g. **Viscosity: constant { Value:0.4 }** ) then I will update the svFSI tool. 

We have postponed the SV release to get the svFSI tool updated, some users want to use the latest svFSI solver (they are building it) but it can't use the solver input files written by SV. We need to release SV in January.

**Comment by ktbolt** [comment]
I see where the SV FSI Tool writes out the solver file, some of the changes are simple
```
Face file path (vtp) -> Face file path
Mesh file path (vtu) -> Mesh file path
Save results in a folder -> no longer read, remove it
Name prefix of saved file -> no longer read, remove it
Increment in saving files ->  no longer read, remove it
```
What is more complicated is the **Physics** panel
![fsi-tool-1](https://user-images.githubusercontent.com/23109458/73581010-ab3f4b80-443c-11ea-927b-dceb17eab731.png)

where **Viscosity** can be 
1) constant: parameters = valaue
2) carreau-yasuda: parameters = Limiting high shear-rate viscosity, Limiting low shear-rate viscosity, Shear-rate tensor multiplier  and  Shear-rate tensor exponent
3) cassons: parameters = Asymptotic viscosity and Yield stress

@vvedula22 what else needs to be changed?

**Comment by vvedula22** [comment]
@ktbolt : Sorry for the delay. Yes, some of what you wrote are correct. There are some additional changes too such as 'Residual dB reduction' is not supported anymore. 

As discussed, I am attaching a couple of templates for solving fluid flow with multiple options (Newtonian/non-Newtonian, RCR BC/closed loop with GenBC, input unsteady flow/bct.vtp, BIPN/GMRES-Trilinos-ILUT, etc.). Please include these basic modifications so we have a working plugin. Later, I will add more templates for other physics, linear solver and preconditioners, special boundary conditions, etc.

[svFSI_fluid_Newt_RCR.txt](https://github.com/SimVascular/SimVascular/files/5461341/svFSI_fluid_Newt_RCR.txt)
[svFSI_fluid_nonNewt_GenBC.txt](https://github.com/SimVascular/SimVascular/files/5461342/svFSI_fluid_nonNewt_GenBC.txt)

**Comment by ktbolt** [comment]
I'm starting on this now, will first evaluate the GUI layout to get an idea about what needs to change and then go through the code to see how it works.

**Comment by ktbolt** [comment]
I've updated the GUI with some of the new output options
<img width="425" alt="Screen Shot 2021-05-13 at 9 25 27 PM" src="https://user-images.githubusercontent.com/23109458/118221269-22320500-b432-11eb-8ecc-ff99092aaddb.png">
will clean this up a bit later.

The plugin now writes a solver input file that works with the new svFSI version in GitHub. I'll next add writing the VTK output options.

**Comment by ktbolt** [comment]
I've added processing VTK output options and writing them to the solver input file
```
Save results to VTK format: 1
Name prefix of saved VTK files: results
Increment in saving VTK files: 10
```

Adding a new parameter requires making code changes to five files, wonder if this could be simplified.

**Comment by ktbolt** [comment]
I've added some widget documentation.

**Comment by ktbolt** [comment]
I've merge into the SV master branch.
