### ISSUE TITLE
Issue post-processing - svpost

### ISSUE THREAD

**Issue by gaetanoaran** [SimVascular/SimVascular#593]
**Describe the bug**
We are running a simulation with openmpi in a cluster with 36 cores, post-processing stops at a certain timestep.
We tried to run the simulation on another computer and the problem is the same, even if it goes a little further.
Until the January update, post-processing worked correctly

**Expected behavior**
We expect post-processing to work correctly to give the results as .vtp and .vtu files

**Desktop**
 - OS: Windows 10
 - SimVascular Version [e.g. 2019-08-09]

**Comment by ktbolt** [comment]
@gaetanoaran Are you running svpost from the command line or within SV?

**Comment by ktbolt** [comment]
@gaetanoaran sorry for the late replay, I'm not getting GitHub emails from this issue. 

You've tried svpost from the command line on the cluster and that failed? Can you please post the command you used? I wondering if svpost is user too much memory and being killed.

svpost has problems on Windows, you will need to execute svpost-bin.exe directly and not use the bash script.

**Comment by gaetanoaran** [comment]
@ktbolt you answered me on public forum for the same issue! 

thanks
Gaetano
