### ISSUE TITLE
ERROR: License is expired

### ISSUE THREAD

**Issue by rohanshad** [SimVascular/SimVascular#637]
**Describe the bug**
License expired error

**To Reproduce**
running svFSI from command line elicits the following error:
```
  ----------------------------------------------

    SimVascular Fluid-Structure Interaction
                  (svFSI v8)

  ----------------------------------------------

  This program comes with ABSOLUTELY NO WARRANTY
  Compiled on 01-30-2020

 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 ERROR occured, see below for more explanation
 ERROR: License is expired
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 STOP All processors are forced to stop by a fatal error
```

**Sherlock cluster (please complete the following information):**
 Using custom fork of Noelias svFSI solver. Everything appeared to be working until recently when this license error showed up.

**Comment by ktbolt** [comment]
This error is caused by legacy code checking for a valid license to use the code against the current date. The license expired in 2019. I don't know why this code was not removed from svFSI, some historical thing I guess.

We are in the process of releasing a new version of the svFSI solver that will fix this problem, hope to get this out within a couple of weeks.

**Comment by rohanshad** [comment]
If possible, could you direct me to the bits of code that needed to be removed to get it working? Some of Noelia’s work was never moved into the production svFSI solver by Vijay because of the way data was handled by the advection diffusion solver, and I don’t know if I can port over Noelias work on the new svFSI solver from scratch 


Rohan

On Jan 30, 2020, at 4:53 PM, Dave Parker <notifications@github.com> wrote:

This error is caused by legacy code checking for a valid license to use the code against the current date. The license expired in 2019. I don't know why this code was not removed from svFSI, some historical thing I guess.

We are in the process of releasing a new version of the svFSI solver that will fix this problem, hope to get this out within a couple of weeks.

**Comment by rohanshad** [comment]
If possible, could you direct me to the bits of code that needed to be removed to get it working? 

Some of Noelia’s work was never moved into the production svFSI solver by Vijay because of the way data was handled by the advection diffusion solver, and I don’t know if I can port over Noelias work on the new svFSI solver from scratch

**Comment by ktbolt** [comment]
I don't have the old svFSI code, it was overwritten by the new code. I looked in the MUPFES code (svFSI originated from that code) and see in the MOD.f file
```
      INTEGER, PARAMETER :: maxnsd = 3, version = 8, maxNProp = 30,
     3   expDate(3)=(/2020,1,1/)
```
and in READFILES.f I see
```
         IF (tArray(1).GE.expDate(1) .AND. tArray(2).GE.expDate(2)
     2      .AND. tArray(3).GE.expDate(3)) err = "License is expired"
```

Look in the READFILES.f in your svFSI code and see if you can find **expDate** anywhere, remove that if-statement from READFILES.f.

**Comment by rohanshad** [comment]
Commenting out lines 154 and 155 fixed this, thanks for the help!
