### ISSUE TITLE
SV takes a long time loading models or freezes computer

### ISSUE THREAD

**Issue by suhaasa** [SimVascular/SimVascular#638]
I've noticed for the latest version of SV, my models take a very long time to load (multiple hours). What I specifically mean is the time it takes from when I double click on the model in the nagivator and the time it displays (frozen until then). In a worst case scenario, the program will simply just crash/lock up the computer. In older versions, it would take a while, but no where near as long (less than 5min).

The current work-around I'm using is to open the old gui in the latest version and work on my models there because of the significantly reduced loading times (<1min) and fast rendering speed. 

A related enhancement that would be nice is an option to toggle whether or not I want all my models loaded on the initialization of the project. This would reduce the project load time significantly for me.

To reproduce: Load a model with hundreds of outlets (let me know if you need one to test).

Expected: model loads within 2-5min

**Comment by ktbolt** [comment]
I see what the problem is. When selecting a model face information is added to the **Face List** table. Every time a face is added to the table a function is called to update the **Blend** table. The **Blend** table is of size num_faces*num_faces!

There are several efficiency problems that need to be resolved here, the first being not creating a num_faces*num_faces **Blend** table.

**Comment by suhaasa** [comment]
Ah I see why that could be a problem! Let me know if you end up fixing it, but no rush.

**Comment by ktbolt** [comment]
I added blocking signals to the  **Face List** table widget when initializing. 

The Healthy Pulmonary project (208 faces) originally took 43 seconds to come up, now takes less than 1 second.

**Comment by ktbolt** [comment]
@suhaasa Could you put your model somewhere I can download it, like to see how long it takes to load it, might need further work on this.

**Comment by ktbolt** [comment]
I did another test on one of Melody's models, 323 faces, originally took 285 secs to come up, now takes < 1 sec.

**Comment by suhaasa** [comment]
Oh that looks really promising! Here's where you can download the parasolid model.

https://drive.google.com/file/d/1ERwuFIqdPmkkVI_8O6ZTeJsqQHCK1ula/view?usp=sharing

**Comment by ktbolt** [comment]
It took < 1 sec to load your model. 

@melodydong I think you too will be pleased with this result.

**Comment by suhaasa** [comment]
great! Is this going in the next version or can you make a build for me to install soon?

Thanks,

Suhaas

**Comment by melodydong** [comment]
This is great! I've also had some long waiting times to load models before, so this will be helpful!

**Comment by ktbolt** [comment]
@suhaasa I just did a pull request for the changes to merge into SV master. I'm not sure when we will cut a new SV version so I can create an installer for you if you want. Ubuntu 16 or 18?

**Comment by suhaasa** [comment]
Ubuntu 16.04 - thanks!
