### ISSUE TITLE
Convert legacy path and contour files to the current XML format using Python API

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/SimVascular#646]
The current Python API does not have functions to read legacy path and contour files. This would be useful to help convert legacy file to the current XML format.

Add functions that can be called from the Python API to read read legacy path and contour files.

**Comment by ktbolt** [comment]
The code for reading legacy files is in sv4gui/Modules for some reason and uses Qt. This makes it impossible to add to existing Python modules, don't reference Qt and Mitk and problems with cyclic shared libraries. I will create new modules for these guys.

**Comment by ktbolt** [comment]
@mrp089 I've created two new Python modules named **PathLegacyIO** and **SegmentationLegacyIO**.  These are implemented in the GitHub branch https://github.com/ktbolt/SimVascular/tree/read-legacy-files
```
SimVascular/Code/Source/sv4gui/Modules/Path/sv4gui_PathLegacyIO_init_py.cxx
SimVascular/Code/Source/sv4gui/Modules/Segmentation/sv4gui_SegmentationLegacyIO_init_py.cxx
```

Use the **SegmentationLegacyIO.Convert()** method to convert a legacy segmentation file named **aorta** and write a **aorta.ctgr** file to **output_dir**.
```
import sv
file_name = "./legacy-segmentations/aorta"
sv.SegmentationLegacyIO.Convert(file_name=file_name, output_dir="./converted-segmentations")
```

Use the **PathLegacyIO.Convert()** method to convert a legacy path file named **0005_1001-cm.paths** and write a **.pth** file for each path to **output_dir**

```
import sv
file_name = "./legacy-paths/0005_1001-cm.paths"
sv.PathLegacyIO.Convert(file_name=file_name, output_dir="./converted-paths")
```
If you need other methods or want the Convert() method to work differently then I can make the changes you need.

**Comment by mrp089** [comment]
Thanks @ktbolt! Works like a charm :+1:

**Comment by ktbolt** [comment]
Cool! I will close this for now. Just reopen this Issue if you need other functionality.

**Comment by mrp089** [comment]
Further testing revealed there is a problem when trying to edit a segmentation in SimVascular:

> Make sure the path for the contour group exits!

For OSMSC 0110_0001, I compared path and segmentation output for SimVascular and Python API. There are some differences, shown here for the aorta:

Path SimVascular
```html
<path id="100" method="0" calculation_number="300" spacing="0" reslice_size="5" point_2D_display_size="" point_size="">
```
Path Python API
```html
<path id="-1" method="0" calculation_number="100" spacing="0">
```

It seems like the `path id` is missing, although the screen output of `sv4SegmentationIO_Convert` during conversion is correct. Adding the `path id` get's rid of the error message.

Segmentation SimVascular
```html
<pos x="-2.939" y="-3.02" z="15.135999999999999" />
...
<control_points>
    <point id="0" x="-2.91648709811822" y="-2.98352551288605" z="15.177326493554633" />
    <point id="1" x="-2.63216193597275" y="-2.69920035074057" z="15.536558091043737" />
</control_points>
```

Segmentation Python API
```html
<pos x="-29.389999" y="-30.200001" z="151.360001000000011" />
...
<control_points />
```

There seems to be a factor 10 difference in `pos` (under `path_point id`). The contours are thus not shown at the right location. Also, the `control_points` are missing (not sure what they do).

**Comment by ktbolt** [comment]
@mrp089 I see what is going on with the path. The code I copied from SV needs to set more information, like path ID, in the PathGroup that is used to write out paths. I will fix that.

I'm not sure what is going on with the segmentations, need to dig more into that. The control points define mean different things for different contour types, for circle they are the center and a point on the circle.

**Comment by ktbolt** [comment]
@mrp089 I've fixed the path problem.

Looking in the SV code that reads in legacy segments I see the comment
```
// update path points using posID, since path point data is wrong sometimes form contour group file
```
and there is code that sets the segmentation path point position **<pos x= y= z=>** from the path point. 

I will modify the Python **SegmentationLegacyIO.Convert()** method to read in a path associated with the segmentation so that I can set the segmentation path point position from the path data.

**Comment by ktbolt** [comment]
@mrp089 I was a bit careless before, didn't dig deep enough into the code to get all the details right. Things are now working.

The Python **SegmentationLegacyIO.Convert()** method now has a .pth path file used to set the contour pos
```
file_name = "./osmc-legacy-segmentations/right_iliac"
path_file_name = "./osmc-converted-paths/right_iliac.pth"
out_dir = "./osmc-converted-segmentations"
sv.SegmentationLegacyIO.Convert(file_name=file_name, path_file=path_file_name, output_dir=out_dir)
```
The Python .ctgr now matches the SV .ctgr. 

Give it a try!

**Comment by mrp089** [comment]
@ktbolt This works great!

After testing with the OSMSC repository, I found that there were many instances in our data where the names of path and segmentation didn't match. @osmsc thus suggested matching paths and segmentations not by their name but by their `pathId` instead.

The input of `sv.SegmentationLegacyIO.Convert` would therefore not be the converted path in `.pth` format, but the original `.paths` file. Do you think this could work?

**Comment by ktbolt** [comment]
@mrp089 Please provide an example here of data where the names of path and segmentation didn't match. I'll modify sv.SegmentationLegacyIO.Convert() to take a .paths file.

**Comment by ktbolt** [comment]
@mrp089 I've modified the sv.SegmentationLegacyIO.Convert()  method to take a legacy path file
```
file_name = "./osmc-legacy-segmentations/0001_0001_groups-cm/lt_sbclvn_FINAL"
path_file_name = "./osmc-legacy-paths/0001_0001-cm.paths"
out_dir = "./osmc-converted-segmentations/0001_0001"
sv.SegmentationLegacyIO.Convert(file_name=file_name, path_file=path_file_name, output_dir=out_dir)
```

The output is
```
$ osmc-converted-segmentations/0001_0001/lt_sbclvn_FINAL.ctgr
$ more $ osmc-converted-segmentations/0001_0001/lt_sbclvn_FINAL.ctgr
<?xml version="1.0" encoding="UTF-8" ?>
<format version="1.0" />
<contourgroup path_name="lt_sbclvn_FINAL" path_id="600" reslice_size="5" point_2D_display_size="" point_size="">
    <timestep id="0">
        <lofting_parameters method="nurbs" sampling="60" sample_per_seg="12" use_linear_sample="1" linear_multiplier="10" use_fft="0" num_modes="20" u_degree="2" v_degree="2" u_knot_type="derivative" v_knot_type="average" u_parametric_type="centripetal" v_parametric_type="chord" />
        <contour id="0" type="Contour" method="Legacy" closed="true" min_control_number="2" max_control_number="2" subdivision_type="0" subdivision_number="0" subdivision_spacing="0">
            <path_point id="4">
                <pos x="-1.08695" y="-1.277486" z="-18.159031" />
                <tangent x="0.123626" y="-0.160642" z="0.97924" />
                <rotation x="0" y="0.98681" z="0.161884" />
            </path_point>
            <control_points>
                <point id="0" x="-0.907308723560188" y="-1.6286407573637" z="-18.2393162572103" />
                <point id="1" x="-0.726052179325911" y="-1.44738421312942" z="-18.232464625086" />
            </control_points>
            <contour_points>
```
Give it a try!

**Comment by mrp089** [comment]
Thank you again @ktbolt! Checked with the repository, works as expected :thumbsup:

**Comment by ktbolt** [comment]
@mrp089 Super! 

I'll keep this issue open for a bit, just in case. If you need other functionality let me know.
