### ISSUE TITLE
Integrate new 3D-1D pipeline in GUI

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#657]
@ktbolt I need your help with connecting the new pipeline in #655 to the SimVascular GUI:

- [ ] Allow the user to select: number of segments per branch, minimum segment length, adaptive meshing (yes/no)
- [ ] Allow different boundary conditions in the same model (e.g. coronary and RCR) and pass to the 3D-1D pipeline
- [ ] Maybe some cool visualization tools (1D model, cross-sectional area,  ...)

**Comment by ktbolt** [comment]
For the GUI tasks I will

1) Add to to the **1D Mesh** panel widgets to select: number of segments per branch, minimum segment length, adaptive meshing (yes/no) .

2) Add **coronary** BC as another option in **BC Type** list and a popup to set parameters.

@mrp089 What are the parameters needed for the ** coronary** BC?

**Comment by mrp089** [comment]
@ktbolt The format that SimVascular already uses is fine. The constants are `p1, p2, q0, q1, q2, b1` from [H. J. Kim et al. "Patient-Specific Modeling of Blood Flow and Pressure in Human Coronary Arteries"](https://link.springer.com/article/10.1007/s10439-010-0083-6), p. 3198

**Comment by ktbolt** [comment]
I've added the number of segments per branch, minimum segment length, and adaptive meshing parameters to the GUI 

<img width="390" alt="Screen Shot 2020-12-10 at 7 37 33 PM" src="https://user-images.githubusercontent.com/23109458/101858854-4bff9c80-3b1f-11eb-940d-756a85dd8bd8.png">

I also added a `mesh_props` element to the XML .s1djb file to store them
```
        <mesh_props>
            <prop key="Adaptive Meshing" value="1" />
            <prop key="Minimum segment length" value="2.000000" />
            <prop key="Number of segments per branch" value="10" />
        </mesh_props>
```

@mrp089 I need to know the  argument names for these guys so I can pass them to the `generate_1d_mesh` Python script. And what should the default values be that are displayed in the GUI?

**Comment by mrp089** [comment]
Looks great @ktbolt!

The [variables](https://github.com/SimVascular/SimVascular/blob/a33e7f809fd779d0f762fa2b8fe7eddb157f80ca/Python/site-packages/sv_1d_simulation/generate_1d_mesh.py#L79-L81) and their [default values](https://github.com/SimVascular/SimVascular/blob/a33e7f809fd779d0f762fa2b8fe7eddb157f80ca/Python/site-packages/sv_1d_simulation/parameters.py#L87-L94) are:

- Adaptive Meshing: ```seg_size_adaptive (False)```
- Number of segments per branch: ```seg_min_num (1)```

I want the legacy behavior of one segment per branch as the default option. For that, I think it's easier to not have the segment length (~~Minimum~~ segment length: ```seg_size (9999) ```) in the GUI.

**Comment by ktbolt** [comment]
@mrp089 Does the 1D solver allow different boundary conditions (e.g. resistance and RCR) in the same model? The **generate_1d_mesh.py** script does not currently support this.

**Comment by mrp089** [comment]
@ktbolt Yes! This is handled in ```mesh.py```. Parameters are only passed from ```generate_1d_mesh.py``` to ```mesh.py``` (and the names of the parameters didn't change, only their interpretation)

Currently, there is in code ```mesh.py``` to convert the old format to the new format (see the documentation in #740):
https://github.com/SimVascular/SimVascular/blob/a33e7f809fd779d0f762fa2b8fe7eddb157f80ca/Python/site-packages/sv_1d_simulation/mesh.py#L212-L214

**Comment by ktbolt** [comment]
@mrp089 There is a single parameter a single parameter `outflow_bc_input_file` but there are two files so do I set `outflow_bc_input_file` to both of those files separated by a space?

**Comment by mrp089** [comment]
@ktbolt new behavior:
- `OUTFLOW_BC_TYPE`: list of all boundary condition file names (e.g. `['rcrt.dat', 'resistance.dat']`)
- `OUTFLOW_BC_INPUT_FILE`: path to folder containing boundary condition files (e.g. `'sim_folder'`)

**Comment by ktbolt** [comment]
@mrp089 The new behavior has been implemented and seems to work. I added coronary BCs but when creating the solver input file I get
```
[generate-1d-mesh] ERROR - The number of BC values 4 do not match the number of outlets 5.
```

In parameters.py line 75 I see
```
        self.OUTFLOW_BC_TYPES = {OutflowBoundaryConditionType.RCR : "rcrt.dat",
                                 OutflowBoundaryConditionType.RESISTANCE : "resistance.dat"}
```

Are coronary BCs supported?

**Comment by mrp089** [comment]
@ktbolt It looks like those lines are unused (```grep -irl OUTFLOW_BC_TYPES``` shows only ```parameters.py```) and can be deleted:
https://github.com/SimVascular/SimVascular/blob/a33e7f809fd779d0f762fa2b8fe7eddb157f80ca/Python/site-packages/sv_1d_simulation/parameters.py#L75-L76


Coronary BCs are supported and tested. I think this is a legit error message, indicating it only got 4 boundary conditions for a geometry that has 5 outlets:
https://github.com/SimVascular/SimVascular/blob/a33e7f809fd779d0f762fa2b8fe7eddb157f80ca/Python/site-packages/sv_1d_simulation/mesh.py#L222-L225

**Comment by ktbolt** [comment]
@mrp089 The problem was that the cort.dat file format I was generating was wrong. I added creating the cort.dat file like is done in svSolver but adding in a face name.

This seems to be working now, generating a solver.in file
```
SEGMENT branch6_seg0 6 16.833629066606875 168 12 13 2.355854860773089 1.0986821516482552 0.0 MAT1 NONE 0.0 0 0 CORONARY CORONARY_3

DATATABLE CORONARY_3 LIST
-1.0 923.6002282753436
-1.0 134750.6704398519
-1.0 8.559389206655454e-07
-1.0 6.9253490715056814e-06
-1.0 41461.729331872695
-1.0 0.0
0.0 14271.0
0.001 14440.0
0.002 14628.0
0.003 14835.6
0.004 15063.6
.
.
.
ENDDATATABLE
