### ISSUE TITLE
Simulation tool does not create walls_combined.vtp 

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/SimVascular#672]
I've created a boundary layer mesh using regional refinement (sphere) that separates the mesh into disjoint regions. 

<img width="608" alt="Screen Shot 2020-06-09 at 6 34 56 PM" src="https://user-images.githubusercontent.com/23109458/84217039-f5d27380-aa7f-11ea-9f75-73ec7fc7b957.png">

When generating data files in the Simulation tool the **walls_combined.vtp** file is not created. Two **combined_connected** files are instead generated.
```
walls_combined_connected_region_0.vtp
walls_combined_connected_region_1.vtp
```
This happens only when boundary layer meshing is enabled.

**Comment by ktbolt** [comment]
@JonathanPham Is there a work-around for this (e.g. using a face edge size) or is this a show-stopper for you?

**Comment by JonathanPham** [comment]
@ktbolt On second thought, I think it would be easier if I could avoid using Parasolid + MeshSim and just this sphere-based regional refinement method in SimVascular's TetGen instead. Do you have time to tackle this issue? If not, no worries!

**Comment by ktbolt** [comment]
@JonathanPham If you say `no worries` then I will not look into this now. But  If this is a show-stopper preventing you from doing your research then you must tell me this and I will find time to look into it.

**Comment by JonathanPham** [comment]
@ktbolt It's a show-stopper. I would appreciate it if you could make some time to look into it. Thanks!

**Comment by ktbolt** [comment]
When meshing with a boundary layer a new face is created for the sphere refinement region (blue)

<img width="744" alt="Screen Shot 2022-02-24 at 2 55 43 PM" src="https://user-images.githubusercontent.com/23109458/155622921-25b958d1-e765-49ab-ade3-f01080c972fb.png">

I am going to add an SV API function to generate the mesh-complete files, just too slow starting up SV, selecting a project, select the mesh tool, select the Simulation tool, write simulation files every time when testing to figure how the code works.

**Comment by ktbolt** [comment]
@JonathanPham Upload your SV project somewhere I can download it.

**Comment by JonathanPham** [comment]
@ktbolt Thanks for tackling this issue for me! I uploaded my project to skalak: `/home/SHARED/forDave/0002_0001.tar.gz`

**Comment by JonathanPham** [comment]
@ktbolt For the example file that I uploaded, it looks like maybe the `GlobalElementID` cell data got messed up during the volume meshing process too. For example, there are two cells with the same `GlobalElementID` (173622) in the `mesh-complete.exterior.vtp` file.

**Comment by ktbolt** [comment]
@JonathanPham The `GlobalElementID` in the .vtp file refers to a 3D element ID in the .vtu file. The two triangles you highlighted belong to the same 3D tetrahedron element so they have the same element ID.

**Comment by ktbolt** [comment]
New faces are created in `MMGUtils_SurfaceRemeshing()` when re-meshing the model surface. For meshing without a boundary layer the function `ResetOriginalRegions()` is called to reset the `ModelFaceID` array by doing a spatial search to match the new face IDs to the original. This function is not called when performing boundary layer meshing. 

This bug has been around since day one so it is interesting that it does not matter to svSolver that there are missing elements in the `walls_combined.vtp` file.

**Comment by ktbolt** [comment]
@JonathanPham I've added code to fix this and tested on the SV project you sent me. Here is a visualization of the `mesh-complete.exterior.vtp` file.

<img width="775" alt="Screen Shot 2022-02-28 at 12 16 20 PM" src="https://user-images.githubusercontent.com/23109458/156059317-d33f7588-3d73-4cbb-8ca8-b012b885f70a.png">

The `walls_combined.vtp` is now being created.

I've merged the changes into the SV master branch. Please test!
