### ISSUE TITLE
63.44 core.mod.apputil.baseApp ERROR: Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by unsolvedsajib** [SimVascular/SimVascular#680]
![105003409_358191548477923_3457230565687335332_n](https://user-images.githubusercontent.com/37798495/85226821-55733c00-b3fb-11ea-8c39-15a0b02fff12.png)

Looking like this when I try to open simvascular

**Comment by ktbolt** [comment]
@unsolvedsajib Could you give me a bit more information, like what SV version you are using, what OS, etc. Also post the contents  of the window SV is launched from.

This appears to be a driver problem. Do other graphics programs work OK?

**Comment by unsolvedsajib** [comment]
SV version: 2020-04-06
SV solver: 2019-05-28

MS windows 10 .

SV is launched from desktop. No other programs were running then.

All other programs are working completely fine except for this SimVascular.


Can you please help me solve this?

**Comment by ktbolt** [comment]
@unsolvedsajib Could you please post the contents of the window SV is launched from. 

On a Window's machine SV stores state information in the folder C:\Users\<UserName>\AppData\Local\SimVascular (you will need to turn on viewing Hidden Items in File Explorer to see this folder). Try removing everything in this folder and see if that fixes things.

**Comment by unsolvedsajib** [comment]
Thank you for reaching out Sir. The program ran successfully. It was
because of my graphics processor. Turns out, SV doesn't do well in intel
graphic processors. But, when I ran the program on my nvidia graphics
processor. it ran perfectly.

**Comment by ktbolt** [comment]
@unsolvedsajib   I'm glad you are up and running! 

It is good to know the potential problems with Intel graphics cards.
