### ISSUE TITLE
Broken installation that cannot be fixed with uninstall/reinstall

### ISSUE THREAD

**Issue by agstraccia** [SimVascular/SimVascular#685]
**Describe the bug**
I originally installed Simvascular version 19.08.09 on my desktop and had no issues segmenting DICOMs. I eventually upgraded to version 20.04.06 and also downloaded svSolver. I could import an STL, create a mesh, and run the solver without issue. However, at some point, my installation broke and the GUI no longer gave the correct options when I right-clicked in the tree (see broken_GUI_model_tree.png) or when I selected features in the tree to modify like the model, mesh, etc. (see broken_GUI_tool_greyed_out.png). This is true for both newly created projects and old projects that I open.

So far, I have tried deleting the installation directory on my C: drive, or using the installation executable to uninstall the program, then reinstalled version 20.04.06 and restarted the computer. This didn't fix the behavior. I have also tried reinstalling version 19.08.09, but I am seeing the same broken behavior.

I installed version 20.04.06 on my personal laptop and was able to open the project that I had previously made and get all of the normal GUI options, so I do not think the project is corrupted. 

I am concerned that even uninstalling Simvascular, restarting my computer, and reinstalling a new version still results in the same broken GUI behavior. It was previously working on that desktop, so theoretically it shouldn't be an issue with the OS. 

**Expected behavior**
When I right click on features in the tree like "Models", I should see options like "Import Solid Model". When I select subnodes to model tree features like "Models" e.g., the model that I imported , I should be able to open the "SV Modeling" tool and change options. 

**Screenshots**
![broken_GUI_model_tree](https://user-images.githubusercontent.com/67807129/86497922-60519900-bd38-11ea-8066-88c60fd9ce3f.png)
![broken_GUI_tool_greyed_out](https://user-images.githubusercontent.com/67807129/86497921-5fb90280-bd38-11ea-8190-291affd38011.png)

**Desktop (please complete the following information):**
 - OS: WIndows Server 2019 Standard
 - SimVascular Version: 19.08.09 and 20.04.06
 - Medical Image Filetype: not important 
 - Imported solid model type: STL

**Additional context**

**Comment by ktbolt** [comment]
@agstraccia On a Window's machine SV stores state information in the folder C:\Users<UserName>\AppData\Local\SimVascular (you will need to turn on viewing Hidden Items in File Explorer to see this folder). Try removing everything in this folder and see if that fixes things.

**Comment by agstraccia** [comment]
Hi @ktbolt , thanks for the quick response. That fixed it! Such a relief, I wasn't sure what was going on. Have a great weekend.

**Comment by ktbolt** [comment]
@agstraccia Glad you are up and running! 

@osmsc We need to add this Windows update problem to the SV documentation. I guess this should go in https://github.com/SimVascular/SimVascular/wiki/user_trouble_shooting_launching_simvascular.
