### ISSUE TITLE
Modeling issue

### ISSUE THREAD

**Issue by mtmonag** [SimVascular/SimVascular#694]
**Describe the bug**
I cannot get past the segmentation phase of using SimVascular. I have gone through the steps with multiple people and non of us could figure it out. 

**To Reproduce**
1. make segmentations
2. create lofted version to check for accuracy
3. create model
4. turn off previous lofts and models
5. you should be able to see the model, but cannot as nothing shows up, even when you highlight the rows of the chart on the right.

**Expected behavior**
There is nothing in the 3D screen

**Screenshots**
https://docs.google.com/document/d/1CMHz__lRKYNYFPIwY14klOQeOBH2iIXJyEfRvS6-hg8/edit?usp=sharing

File is also a screenshot of the issue, in case the google docs sharing link doesn't work.
![Screenshot of SimVascular Issue](https://user-images.githubusercontent.com/68431986/87795955-bc2b2000-c816-11ea-955f-7c466420135e.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SimVascular Version 2020-04-06
 - Medical Image Filetype: DICOM

**Additional context**
Speed in your reply would be greatly appreciated.

**Comment by ktbolt** [comment]
@mtmonag I've not seen this behavior before. Please copy all the messages that are displayed in the window that SV creates when it starts to a file and attached it here.

If you put your project someplace I can download it I'll have a look.

**Comment by mtmonag** [comment]
Mr. Parker
There aren't any messages, but here is the file. If there is an issue with
the way I sent it, please let me know.
Thanks so much for helping me out!
Matt Monaghan

**Comment by ktbolt** [comment]
@mtmonag Sorry, I don't see the file.

**Comment by mtmonag** [comment]
@ktbolt 
After a second look, the file type is not supported by this forum. Can I email it to you?
Thanks for being willing to help me out!
Matt Monaghan

**Comment by mtmonag** [comment]
@ktbolt Nevermind! It has (miraculously) worked! Thanks for being so willing to help me.

**Comment by ktbolt** [comment]
@mtmonag I'm glad things are working! I'm not sure what was going, maybe you didn't save the project? 

Anyway, if you have other problems let me know.
