### ISSUE TITLE
Simvascular command line example

### ISSUE THREAD

**Issue by npavlovikj** [SimVascular/SimVascular#697]
Dear,

I apologize if I have missed this information in the documentation, but I was wondering how the command-line execution of SimVascular looks like?
I have an Ubuntu image with the `simvascular.exe` executable and I do have *.pth files, but I don't know how to correctly run the program.
Running it with or without the `-tcl` option gives me various errors, and I because I don't know the exact command I don't know which errors I should try and fix.

I would really appreciate any tips and guidance regarding this question!

Thank you,
Best Regards,
Natasha

**Comment by ktbolt** [comment]
@npavlovikj This kind of question is better for the SimVascular Forum https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=188&pluginname=phpBB, where other users can see the problem and the solution.

If you have installed SimVascular using the Ubuntu installer then you can be run it from the command line using 
```
/usr/local/sv/simvascular/2020-04-06/simvascular
```
but it is most easily run by selecting the SimVascular icon from **Show Applications**.

**Comment by npavlovikj** [comment]
Thank you for the info @ktbolt !
My question was related to the CLI usage of SimVascular, and not the GUI one.
I didn't find related topics in the Forum nor here, thus the question.

Thank you,
Natasha
