### ISSUE TITLE
Scripting support for MeshSim

### ISSUE THREAD

**Issue by suhaasa** [SimVascular/SimVascular#698]
**Is your feature request related to a problem? Please describe.**
Currently, to set local sizes in MeshSim you have to manually select each face and set a mesh size.
**Describe the solution you'd like**
I would like the option to load in a file that could automatically set the local size to each face based on what the text file says.
**Describe alternatives you've considered**
This is implemented in the old gui.
**Additional context**
This is file that you can load into the old gui, not sure if its translatable.
[full_modelv071520_lca_0col.txt](https://github.com/SimVascular/SimVascular/files/4939955/full_modelv071520_lca_0col.txt)

**Comment by ktbolt** [comment]
@suhaasa When SV starts it reads in  an XML **.msh** Meshing tool files that have the same parameters in the **full_modelv071520_lca_0col.txt** file about
```
<?xml version="1.0" encoding="UTF-8" ?>
<format version="1.0" />
<mitk_mesh type="TetGen" model_name="demo">
    <timestep id="0">
        <mesh type="TetGen">
            <command_history>
                <command content="option surface 1" />
                <command content="option volume 1" />
                <command content="option UseMMG 1" />
                <command content="option GlobalEdgeSize 0.5" />
                <command content="setWalls" />
                <command content="localSize wall_aorta 0.3" />
                <command content="option Optimization 3" />
                <command content="option QualityRatio 1.4" />
                <command content="option NoBisect" />
                <command content="AllowMultipleRegions 0" />
                <command content="generateMesh" />
                <command content="writeMesh" />
            </command_history>
        </mesh>
    </timestep>
</mitk_mesh>
```

All that needs to be done is to add **<command content="localSize wall_aorta 0.3" />** elements to the XML file for the appropriate faces and those values will show up in the GUI and be used when generating a mesh.

**Comment by ktbolt** [comment]
No feedback on this so I'll close for now.
