### ISSUE TITLE
Legacy segmentations not exporting properly

### ISSUE THREAD

**Issue by suhaasa** [SimVascular/SimVascular#707]
**Describe the bug**

When I export segmentations as legacy, the resulting segmentation file is not always in the same order as the original.

**To Reproduce**
1. make a long segmentation group (or use the one I attached (LCA_ordered is a text file, but you can rename it as a ctgr file)
2. export as legacy segmentation
3. import legacy segmentation (or load it in the old gui of SV)
4. See that the segmentations are not ordered properly

**Expected behavior**
I would like the segmentation groups to be ordered properly.

**Desktop (please complete the following information):**
 - OS: Windows 10 and linux
 - SimVascular Version 2020-04-06
 - Medical Image Filetype vti

**Additional context**
I need to do this because I would like to scale the segmentation groups by a factor of 0.001. I have a script that does this with the legacy segmentation file.

![ordered](https://user-images.githubusercontent.com/35112782/90594634-bcb13080-e19f-11ea-9722-c0d97ec47166.PNG)
![not_ordered](https://user-images.githubusercontent.com/35112782/90594636-bcb13080-e19f-11ea-9cab-788ec0003fa4.PNG)

[LCA_not_ordered.txt](https://github.com/SimVascular/SimVascular/files/5094133/LCA.txt)

[LCA_ordered.txt](https://github.com/SimVascular/SimVascular/files/5094137/LCA_ordered.txt)

**Comment by suhaasa** [comment]
Update: It looks like it only doesn't import properly when viewing the old gui. When imported the exported legacy segmentation in the new gui, it works as intended. This bug may not be as big I thought.

**Comment by ktbolt** [comment]
Compatibility between the old and new SV versions is not something I'm going to worry about. 

@suhaasa If you need any additional functionality not found in the new SV version then I can  write you a Python script no problem. I've got lots of examples of scripts I've written for users and can easily put something together.

Here is a Python script used to scale contours https://github.com/ktbolt/cardiovascular/tree/master/scale-contours-ctgr/python

**Comment by suhaasa** [comment]
Okay thanks! Yea agreed, I think this is fine then.
