### ISSUE TITLE
Centerline extraction on a tube fails

### ISSUE THREAD

**Issue by JonathanPham** [SimVascular/SimVascular#711]
**Is your feature request related to a problem? Please describe.**
Generating centerlines for a tube (one inlet and one outlet, not necessarily a perfect cylinder) from the SimVascular Python code in SimVascular/Python/site_packages/sv_1d_simulation/generate_1d_mesh.py leads to a segmentation fault error.

**Describe the solution you'd like**
Is there an easy way to generate the centerlines for these simple tubes (again, not necessarily a perfect cylinder)? Is it possible to add a feature in the SimVascular Python codes to perform this centerline extraction for us?

Thanks!

**Comment by ktbolt** [comment]
@JonathanPham Attach a model here that is failing.

**Comment by JonathanPham** [comment]
I attached the mesh files for a simple tube, as well as the python script (**generate_centerlin
[centerline_generation.zip](https://github.com/SimVascular/SimVascular/files/5144353/centerline_generation.zip)
es.py**) that I used to generate the centerline, here. I tried running generate_centerlines.py with the command, **sv --python -- generate_centerlines.py**, which ultimately yields a seg fault error.

**Comment by ktbolt** [comment]
This works fine using the new Python API.
![Screen Shot 2020-08-28 at 3 40 04 PM](https://user-images.githubusercontent.com/23109458/91620472-e9560c80-e944-11ea-9f7d-03c9224a3246.png)

I'm not able to run your script, get the error
```
    centerlines = vmtkscripts.vmtkCenterlines()
NameError: name 'vmtkscripts' is not defined
```

Btw, I've never extracted centerlines using `sv_1d_simulation.generate_1d_mesh` and have not ever tested it.

**Comment by JonathanPham** [comment]
Hmm, I don't get the vmtkscripts error when I run it on my end. But okay, sounds good. Thanks for looking into this for me, Dave!

**Comment by JonathanPham** [comment]
Hmm, I don't get the vmtkscripts error when I run it on my end. But okay, sounds good. Thanks for looking into this for me, Dave!

**Comment by JonathanPham** [comment]
Hmm, I don't get the vmtkscripts error when I run it on my end. But okay, sounds good. Thanks for looking into this for me, Dave!

**Comment by JonathanPham** [comment]
Hmm, I don't get the vmtkscripts error when I run it on my end. But okay, sounds good. Thanks for looking into this for me, Dave!

**Comment by JonathanPham** [comment]
Hmm, I don't get the vmtkscripts error when I run it on my end. But okay, sounds good. Thanks for looking into this for me, Dave!

**Comment by JonathanPham** [comment]
Hmm, I don't get the vmtkscripts error when I run it on my end. But okay, sounds good. Thanks for looking into this for me, Dave!

**Comment by ktbolt** [comment]
This error comes from using the SV released version which is different from the source version you are using. Note that the `sv_centerlines` code in the latest source is no longer compatible with the new Python API.

**Comment by JonathanPham** [comment]
Okay, got it. I'll try to update my scripts to make them compatible with the new Python API. Thanks for your help, Dave!
