### ISSUE TITLE
Hard to use levelset method

### ISSUE THREAD

**Issue by 447983454** [SimVascular/SimVascular#712]
The levelset method doesn't work on my data. I have tried to configure the parameters many times but it still cannot work.
Is there any trick in the parameter setting, or anything wrong about my data?
I attach my data link here. I would be very grateful to see any suggestions! Please help!
[https://drive.google.com/file/d/1Wp_QbeJHDQsjW77MRQ5La6hJSOmWlQRI/view?usp=sharing](url)
<img width="1007" alt="截屏2020-08-29 下午5 09 42" src="https://user-images.githubusercontent.com/20389539/91633507-4ae8aa80-ea1b-11ea-835d-44acdf77b873.png">

**Comment by ktbolt** [comment]
I answered this in the SV Forume.
