### ISSUE TITLE
Errors compiling beta sv with new python API on windows 10 

### ISSUE THREAD

**Issue by zasexton** [SimVascular/SimVascular#731]
**Describe the bug**
Errors compiling from source on SimVascular beta with new python API on windows. 

**To Reproduce**
1. Configure using cmake gui and existing binaries (Release)
2. generate files for VS project
3. Build ALL in VS 

**Screenshots**
![compile_errors_sv](https://user-images.githubusercontent.com/47196674/92983247-061b3580-f457-11ea-9de7-92027448ccf9.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SimVascular Version source cloned 9-11-20

**Additional context**
Using msvc 2017 compiler and cmake gui.

**Comment by zasexton** [comment]
Thanks for letting me know Dave!

—
Stanford Bioengineering
NSF Graduate Fellow
________________________________

**Comment by zasexton** [comment]
@ktbolt would it be possible to change line 63 of Python/site-packages/sv/__init__.py to read as:

`elif sys.platform.startswith("linux"):`

I switched to linux to tinker with the new python API (since I've been having trouble with compiling windows from source) and I had some difficulty importing the sv module in the python API because the system platform returns "linux2" for ubuntu 18.04.5 LTS. I understand that this should not be relevant for Python versions later than 3.3 but when I run the simvascular python shell it returns the platform as "linux2"

**Comment by ktbolt** [comment]
@zasexton I thin it would be fine to make that change.

**Comment by osmsc** [comment]
pull request initiated to fix build on Windows

I also had issues with the "linux2" on python so I fixed that in my pull request
