### ISSUE TITLE
Python API: Add centerline splitting

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#739]
Centerlines can currently be extracted in the Python API with the function `sv.vmtk.centerlines`. However, the output centerline is not sufficient to generate 1D models. That requires a second step to split the centerline in branches and junctions.

When hitting the "Calcualte Centerlines" in the GUI, the function `sv4guiModelUtils::CreateCenterlines` in `sv4gui_ModelUtils.cxx` performs both operations:
- `sys_geom_centerlines` to create the centerlines
- `sys_geom_centerlinesections` to perform the splitting

To add centerline splitting to the Python API, there are two options that can both be implemented in `Vmtk_PyModule.cxx`:
1. Add call to `sys_geom_centerlinesections` after call to `sys_geom_centerlines` in function `Vmtk_centerlines`
2. Add a separate function with its own inputs to call `sys_geom_centerlinesections`

Both options have advantages. Option 1 reproduces the behavior of the GUI and would be easier to use (only one function call with minimal input parameters). Option 2 would support users' legacy code that works with the "raw" VMTK centerline.

My favorite is option 1. This can be easily implemented:
```diff
diff --git a/Code/Source/PythonAPI/Vmtk_PyModule.cxx b/Code/Source/PythonAPI/Vmtk_PyModule.cxx
index 8849f65d..ddbe2c83 100644
--- a/Code/Source/PythonAPI/Vmtk_PyModule.cxx
+++ b/Code/Source/PythonAPI/Vmtk_PyModule.cxx
@@ -456,13 +456,21 @@ Vmtk_centerlines(PyObject* self, PyObject* args, PyObject* kwargs)
 
   // Calculate the centerlines.
   cvPolyData* linesDst = nullptr;
+  cvPolyData* linesDstTmp = nullptr;
   cvPolyData* voronoiDst = nullptr;
+  cvPolyData* surfGrouped = nullptr;
+  cvPolyData* sections = nullptr;
   //std::cout << "[Vmtk_centerlines] Calculate centerlines ... " << std::endl;
 
-  if (sys_geom_centerlines(&cvSurfPolydata, sources.data(), numInletIds, targets.data(), numOutletIds, &linesDst, &voronoiDst) != SV_OK) {
+  if (sys_geom_centerlines(&cvSurfPolydata, sources.data(), numInletIds, targets.data(), numOutletIds, &linesDstTmp, &voronoiDst) != SV_OK) {
       api.error("Error calculating centerlines.");
       return nullptr;
   }
+
+  if (sys_geom_centerlinesections(linesDstTmp, &cvSurfPolydata, &linesDst, &surfGrouped, &sections) != SV_OK) {
+      api.error("Error splitting centerlines.");
+      return nullptr;
+  }
   //std::cout << "[Vmtk_centerlines] Done. " << std::endl;
 
   return vtkPythonUtil::GetObjectFromPointer(linesDst->GetVtkPolyData());

```

**Comment by ktbolt** [comment]
I've added an optional `split` argument to `sv.vmtk.centerlines()` that is True by default. Computing centerlines using
```
centerlines_polydata = sv.vmtk.centerlines(model_polydata, inlet_ids, outlet_ids, use_face_ids=True)
```
now creates a PolyData object with lots of interesting information

<img width="606" alt="Screen Shot 2020-09-22 at 8 13 44 PM" src="https://user-images.githubusercontent.com/23109458/93963098-1feb3100-fd11-11ea-8044-7502bc0ebef7.png">


You can compute centerlines without branching informations using
```
centerlines_polydata = sv.vmtk.centerlines(model_polydata, inlet_ids, outlet_ids, split=False, use_face_ids=True)
```

**Comment by ktbolt** [comment]
Merged with SV master.
