### ISSUE TITLE
Python API (and GUI): Allow multiple 1D boundary condition types

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#740]
Currently, only one type of boundary condition is allowed in the Python API and in the GUI (either RCR or resistance). However, some simulations require a combination of different boundary conditions.

The Python Code to generate svOneDSolver input files can already handle different kinds of boundary conditions. To work with the Python API and the GUI, two parameters need to be changed.

Old behavior:
- `params.outflow_bc_type`: string with boundary condition type (`'rcr'` or `'resistance'`)
- `params.outflow_bc_file`: path to file containing boundary conditions (e.g. `'sim_folder/rcrt.dat'`)

New behavior:
- `params.outflow_bc_type`: list of all boundary condition file names (e.g. `['rcrt.dat', 'resistance.dat']`)
- `params.outflow_bc_file`: path to folder containing boundary condition files (e.g. `'sim_folder'`)

**Comment by mrp089** [comment]
@ktbolt I'm reopening this. We fixed this issue for the GUI, but I think the Python API still uses the "old" behavior, which is incompatible with the 1D generation code and allows only one uniform BC type:

https://github.com/SimVascular/SimVascular/blob/86220611e74a4899b0371095324788464a2b8925/Code/Source/PythonAPI/SimulationOneDimensional_PyClass.cxx#L196-L197

https://github.com/SimVascular/SimVascular/blob/86220611e74a4899b0371095324788464a2b8925/Code/Source/PythonAPI/SimulationOneDimensional_PyClass.cxx#L239-L240

I could include code in the 1D generation to catch that, e.g., here:

https://github.com/SimVascular/SimVascular/blob/86220611e74a4899b0371095324788464a2b8925/Python/site-packages/sv_1d_simulation/mesh.py#L219-L222

However, that would still only allow uniform BC types for all outlets.

**Comment by ktbolt** [comment]
I'll add the new behavior, forgot that the Python API is actually used for 1D simulations. 

I'll also update the `SimVascular-Tests/new-api-tests/simulation/one-dimensional` example.

**Comment by ktbolt** [comment]
I've updated the SV Python API to support the new behavior, also added some functions to the Python `BoundaryConditions` class to write bc files.

**Comment by ktbolt** [comment]
I've merged into master.
