### ISSUE TITLE
Python API: 1D time step not passed to input file

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#742]
The `Solution` object of `sv.simulation.OneDimensionalParameters` contains the parameter `time_step` to set the time step for the svOneDSolver input file. However, this parameter is not passed to `generate_1d_mesh.py`. Thus, the default value for the time step `0.000588` is written to the input file.

**Comment by ktbolt** [comment]
@mrp089 Did you fix this or do I still need to?

**Comment by mrp089** [comment]
I haven't fixed it yet. If it's easy for you please go ahead, if not I'm happy to take a look.

**Comment by ktbolt** [comment]
I will fix it.

**Comment by ktbolt** [comment]
Fixed and merged into SV master.
