### ISSUE TITLE
Issues running Simvascular 9-21-20

### ISSUE THREAD

**Issue by suhaasa** [SimVascular/SimVascular#745]
**Describe the bug**
I get this error when trying to run simvascular: 

/usr/local/sv/simvascular/2020-09-21/bin/simvascular: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**To Reproduce**
1. go to /usr/local/sv/simvascular/2020-09-21/bin/
2. run ./simvascular
OR
1. run sudo bash  /usr/local/sv/simvascular/2020-09-21/bin/setup-symlinks.sh
2. run simvascular via terminal

**Desktop (please complete the following information):**
Ubuntu 16.04.6 LTS 64-bit

**Comment by ktbolt** [comment]
@suhaasa It seems that you installed the Ubuntu 18.04 SV version. That will not work on Ubuntu 16.04. I will build an Ubuntu 16.04 installer.

**Comment by ktbolt** [comment]
@suhaasa I've added an Ubuntu 16.04 SV installer to SimTK.

**Comment by suhaasa** [comment]
Thank you!
