### ISSUE TITLE
Segmentation Error

### ISSUE THREAD

**Issue by KamranPoorbahrami** [SimVascular/SimVascular#746]
Hello All, 

I was trying to use region growing 3D segmentation on a set of images (VTK) and I got this error. I do not know what it means because the threshold that I picked using a seed point was -3000 to -2600 and the lower is not greater than the upper. Therefore, I am not sure if it is actually a threshold error or this is something else. 
Did anyone face this problem before?
I also tried different versions of Simvascular (Windows versions).

Thanks
Kamran

"\cygwin64\usr\local\sv\ext\bin\msvc-12.5\x64\itk-4.7.1\include\itk-4.7\itkBinaryThresholdImageFilter.hxx:273:
itk::ERROR: BinaryThresholdImageFilter(000001D362A1BC00): Lower threshold cannot be greater than upper threshold."

**Comment by ktbolt** [comment]
This is being addressed in the SV Forum.
