### ISSUE TITLE
VMTK cap_with_ids does not work

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/SimVascular#749]
When using the cap_with_ids returns error vmtk.Error: Vmtk.cap_with_ids() Error creating cap with ids. "cap" works fine, but does not return proper array name for later steps.

**Comment by ktbolt** [comment]
@schwarz-e I encountered several problems when converting `vmtk.cap_with_ids()`. 

The results produced by the `vmtk.cap_with_ids()` function are confusing. It calls the `sys_geom_cap_with_ids()` function which sometimes creates a **ModelFaceID** data array and sometimes not. When it does create the **ModelFaceID** it can be wrong depending on the ID value used to assign face IDs!

```
>>> capped_cylinder = sv.vmtk.cap_with_ids(surface=model_polydata, fill_id=0, increment_id=True)
produces data arrays

Data name: CapID
  Number of IDs: 3
  IDs: {1, 2, -1}
Data name: ModelFaceID
  Number of IDs: 2
  IDs: {1, 2}
assigns a face ID 1 to both a cap and the wall.
```

I'm thinking to not expose `vmtk.cap_with_ids()` or maybe create another version of `sys_geom_cap_with_ids()` that produces results that you would expect.

**Comment by schwarz-e** [comment]
It's not just that it has weird numbering- it doesn't produce anything (just raises an error). However, ModelFaceID is needed downstream to mesh with sv.mesher.

For the sv.mesher, even after I manually add a ModelFaceID (which it needs but, with this error, cannot generate on its own) I get a segmentation dump. Not sure if this is related.

Also, is there a way to pass the model created from sv.modeling to sv.meshing? right now it seems like you need to save it as a vtp and then load it into the mesher.

**Comment by ktbolt** [comment]
@schwarz-e I think the **vmtk.Error: Vmtk.cap_with_ids() Error creating cap with ids.** is caused by `sys_geom_cap_with_ids()` expecting that a ModelFaceID array is already defined.

I seem to recall that the mesher expects model face IDs to start from 1, 0 has a special meaning.

There is no API method to directly set the model for the mesh, I will add that.

Let me have a look at the SV functions that manipulate cap IDs and implement a new function that does what you want, don't want to modify the existing functions and break SV.

**Comment by schwarz-e** [comment]
Is sys_geom_cap_with_ids() part of the python API? It's not in the documentation.

**Comment by schwarz-e** [comment]
Maybe related- when I manually create a ModelFaceID to try and user the mesher.TetGen, setting mesher.set_walls(face_ids=[1]) raises a Segmentation Fault error: /usr/local/sv/simvascular/2020-09-23/simvascular: line 113:  8447 Segmentation fault      (core dumped) $SV_HOME/bin/simvascular $*

**Comment by ktbolt** [comment]
sys_geom_cap_with_ids() is a function that is part of the SV core code, it
is called by the Python API.

**Comment by ktbolt** [comment]
I've rewritten the SV `sys_geom_cap()` function, the original seemed to be used only for centerline extraction, renamed that to `sys_geom_cap_for_centerlines()`.

The new `sys_geom_cap()` function now creates a **ModelFaceID** CellData DataArray, see the capped PolyData object below

<img width="698" alt="Screen Shot 2020-09-29 at 10 05 39 PM" src="https://user-images.githubusercontent.com/23109458/94645350-77a11380-02a0-11eb-82f7-10bea3439ae3.png">

@schwarz-e Work around for the current API: If you create a solid model from the capped PolyData object, calling `compute_boundary_faces()` creates the **ModelFaceID** CellData DataArray for the model.

```
modeler = sv.modeling.Modeler(sv.modeling.Kernel.POLYDATA)
capped_polydata = sv.vmtk.cap(surface=polydata, use_center=False)
capped_model = sv.modeling.PolyData()
capped_model.set_surface(surface=capped_polydata)
face_ids = capped_model.compute_boundary_faces(angle=60.0)
capped_model.write(file_name="cylinder-surface-capped-model", format="vtp")
```

```
$ more cylinder-surface-capped-model.vtp
<?xml version="1.0"?>
<VTKFile type="PolyData" version="0.1" byte_order="LittleEndian" header_type="UInt32" compressor="vtkZLibDataCompressor">
  <PolyData>
    <Piece NumberOfPoints="4262"                 NumberOfVerts="0"                    NumberOfLines="0"                    NumberOfStrips="0"                    NumberOfPolys="8520"                >
      <PointData>
      </PointData>
      <CellData Scalars="ModelFaceID">
        <DataArray type="Int64" Name="CenterlineCapID" format="appended" RangeMin="1"                    RangeMax="3"                    offset="0"                   >
        </DataArray>
        <DataArray type="Int32" Name="ModelFaceID" format="appended" RangeMin="1"                    RangeMax="3"                    offset="276"                 >
        </DataArray>
      </CellData>

```

**Comment by ktbolt** [comment]
I've added a `set_model()` method to the API **TetGen** mesher class to set the mesher model directly rather than needing to load it from a file

```
modeler = sv.modeling.Modeler(sv.modeling.Kernel.POLYDATA)

cylinder = modeler.cylinder(center=[0.0, 0.0, 0.0], axis=[0.0, 1.0, 0.0], radius=1.0, length=6.0)

face_ids = cylinder.compute_boundary_faces(angle=60.0)

mesher = sv.meshing.TetGen()

mesher.set_model(cylinder)
```

**Comment by ktbolt** [comment]
I merged this with SV master.

**Comment by schwarz-e** [comment]
Hi, it looks like vmtk.cap_with_ids, can this or face remeshing be made available again? vmtk.cap defaults to creating a cap like this with centers on: 

![image](https://user-images.githubusercontent.com/53580464/123720263-85d48e00-d838-11eb-8b72-564c43023226.png)

or this with centers off:

![image](https://user-images.githubusercontent.com/53580464/123720288-9553d700-d838-11eb-9b47-a1f25a030f69.png)

Neither which can be used directly for simulation. Global remeshing is not an option as the wall mesh needs to correspond to the solid mesh boundary.

**Comment by ktbolt** [comment]
@schwarz-e You can use the `sv.mesh_utils.remesh_faces()` function to remesh selected model faces. See https://github.com/SimVascular/SimVascular-Tests/blob/master/new-api-tests/modeling/remesh-faces.py.

**Comment by schwarz-e** [comment]
This is a new to the June 2021 version, right? Will this also be available on the cluster-only version of the python api soon?

**Comment by ktbolt** [comment]
This in the June 2021 version.

I will need to build another another SV cluster-only version; will do that this week, if i can remember how I built it ...

Is the SV cluster-only version working well for your application?

**Comment by schwarz-e** [comment]
The basics are working well, but I can't get the full version of VMTK or VTK to load separately from the version included with the sv modules. In addition, I can't load scipy into the same script using the Python API.

I can kind of work around these problems, but it requires having multiple files and loading/unloading VTK, VMTK, and scipy on the fly which is pretty messy. Is there a way to get full functionality of those python packages while using the API? It would really help it be functional for stand-alone modeling.

Erica Schwarz | she/her
Stanford University | Marsden Lab
520-870-3485 | ***@***.***
________________________________

**Comment by ktbolt** [comment]
@schwarz-e SV Python is its own world, no VMTK and support for a limited number of Python packages due to size limitations for the installers.

What functionality do you need from VMTK? I might could add it to the SV Python `vmtk` module. 

What functionality do you need from VTK that is not in the version (8.1) that we support? 

I would have liked the SV Python API to just be a Python package you could install into a Python distribution but SV was not implemented as an API so there is no way to get this to work (yet!).

`scipy` is now supported in SV Python. It will be in the new `sv-centos7-cluster` version I am building now.

**Comment by ktbolt** [comment]
@schwarz-e The new `sv-centos7-cluster` version is on SimTK. Have at it!
