### ISSUE TITLE
error: no reader availible 

### ISSUE THREAD

**Issue by jche8019** [SimVascular/SimVascular#758]
**Describe the bug**
Basically the title, just had simvascular installed on ubuntu 20, could not load .dcm files with no reader as error.
Wondering if its installation error or there actually isnt a reader for .dcm files by magnetic resonance. 

**Desktop **
 - OS: [ubuntu 20.04]
 - SimVascular Version [2020-09-21]
 - Medical Image Filetype [dcm- MR modality= scan by magnetic resonance ]

**Comment by ktbolt** [comment]
@jche8019 I removed the screen shot, maybe contained PHI.
