### ISSUE TITLE
Python API MeshSim meshing

### ISSUE THREAD

**Issue by suhaasa** [SimVascular/SimVascular#760]
When trying to run this line of code:

sv.meshing.create_mesher(sv.meshing.Kernel.MESHSIM)

I get this error:

meshing.Error: PyMeshing.create_mesher() Unable to create a mesher for the 'MESHSIM' kernel.

Is the MeshSim kernel not implemented yet? The example code runs into the same issue as well.

Suhaas

**Comment by ktbolt** [comment]
@suhaasa Is the MeshSim plugin installed?

**Comment by suhaasa** [comment]
I believe so. These are the lines when I start simvascular:

 PsdU Parasolid: 30.0.167
 
[1.272] Parasolid module loaded.
  MeshSim:     14.0-191014
[1.386] MeshSim module loaded.
[1.693] Load python module

**Comment by suhaasa** [comment]
Ah okay, something is wrong - this is what I get toward the initialization of SV:

------------------- PyInit_PyParasolidPlugin  -----------------
[PyInit_PyParasolidPlugin] Call sv4guiRegisterParasolidFunction() 
 
>>>>>>>>>>>>>>>>> sv4guiRegisterParasolidFunction <<<<<<<<<<<<<<<<
#### ERROR: PK_SESSION_start 
  PsdU Parasolid: 30.0.167
#### ERROR: initializing attribute definition.
#### ERROR: initializing attribute definition.
 
 
[PyInit_PyParasolidPlugin] Done.

**Comment by ktbolt** [comment]
@suhaasa I think the **ERROR: initializing attribute definition.** messages are misleading, not sure why they are being generated, need to comment those out. Create a Parasolid model to make sure that it is OK.

I'll bring up an Ubuntu VM and experiment with the MeshSim mesher, see what errors are generated if the plugin loads but the license is not valid.

**Comment by suhaasa** [comment]
Ah okay, Parasolid works fine for me, and I can regularly mesh using MeshSim via the GUI, so I think my license is fine. I'm running ubuntu 16 and the 09-28 version of SV if that makes a difference.

**Comment by ktbolt** [comment]
@suhaasa Well, looking in **SimVascular-Tests/new-api-tests/meshing/meshsim-mesh.py** I see
```
## Generate the mesh. 
#
# [TODO:DaveP] need to implement this.
#
mesher.generate_mesh(options)
```
so it seems that the **MeshSim** class is half baked, the `generate_mesh()` method is not even documented on the SV web page! Bah!

I will try to get this working tomorrow, first need to build a new VM for Ubuntu 16, old one does not work.

Sorry for the delay!

**Comment by suhaasa** [comment]
No worries, I saw that too, so I figured something might not be up to date - let me know when you get to it!

**Comment by ktbolt** [comment]
I've added processing MeshSim options set in the Python `MeshSimOptions` class, processing options is always a bit involved, many ways to screw this up because SV uses a double array with implicit meaning to set options.

Anyway, I am now able to generate a mesh. 

I now need to change the way mesh face information is returned using the `get_model_face_ids()` method. It currently returns an array of ints `[101, 76, 73, 96, 98]`for the aorta-iliac model. However, these IDs don't work when setting face meshing parameters (e.g. local edge size), MeshSim recognizes IDs `[13, 7, 63, 57, 60]`, these these values appear to be tags set on the model, not sure how.

And the solid model .mdl file defines face IDs as
```
            <faces>
                <face id="1647" name="wall_right_iliac" type="wall" visible="true" opacity="1" color1="1" color2="1" color3="1" />
                <face id="1638" name="right_iliac" type="cap" visible="true" opacity="1" color1="1" color2="1" color3="1" />
                <face id="1692" name="wall_aorta" type="wall" visible="true" opacity="1" color1="1" color2="1" color3="1" />
                <face id="1685" name="aorta" type="cap" visible="true" opacity="1" color1="1" color2="1" color3="1" />
                <face id="1683" name="aorta_2" type="cap" visible="true" opacity="1" color1="1" color2="1" color3="1" />
            </faces>
```

**Comment by suhaasa** [comment]
Thanks for the update! It would be extremely helpful for me if its possible to set the local edge size via the face name i.e.

size wall_aorta absolute 0.015

If there's already an easy mapping between faceID and face name, then that works too.

**Comment by ktbolt** [comment]
Using face names is best but I'm not yet sure how to get that working across all solid modelers and mesh generators, have to give it a think.

**Comment by ktbolt** [comment]
I've modified the `mesher.get_model_face_info()` method to return model face information in a dict

```
>>> face_info = mesher.get_model_face_info()
>>> print("Mesh face info: ")
>>> for key in face_info:
>>>    print("  {0:s}:  {1:s}".format(key, str(face_info[key])))
Mesh face info: 
  id:  ['13', '7', '63', '57', '60']
  modelID:  ['101', '76', '73', '96', '98']
  name:  ['wall_right_iliac', 'right_iliac', 'wall_aorta', 'aorta', 'aorta_2']
```
The **id** face IDs are used by MeshSim, can use those to set local meshing options. The **ModelID** IDs are Parasolid IDs. 

I've also modified the `MeshSimOptions` class to accept int or string values for the **face_id** parameter
```
>>> # Can use 'id' face ID
>>> options.local_edge_size =  [ {'face_id':63, 'edge_size':0.1, 'absolute':True } ]

>>> # or can use 'name' face name
>>> options.local_edge_size =  [ {'face_id':'wall_aorta', 'edge_size':0.1, 'absolute':True } ]
```

This all seems to work but I want to test a bit more.

**Comment by ktbolt** [comment]
I've merged this into master.

**Comment by suhaasa** [comment]
So I tried the sample code it works fine, but when I try to run this bit of code

global_edge_size = { 'edge_size':0.1, 'absolute':True }
options = sv.meshing.MeshSimOptions(global_edge_size=global_edge_size, surface_mesh_flag=True, volume_mesh_flag=True)
print(str(type(options)))

## Set local (face) edge size.
#
#options.local_edge_size =  [ {'face_id':63, 'edge_size':0.1, 'absolute':True } ]
for face in face_info["name"]: 
	if face.startswith("aorta"):
		options.local_edge_size =  [ {'face_id':face, 'edge_size':0.1, 'absolute':True } ]
	elif len(face)<5:
		options.local_edge_size =  [ {'face_id':face, 'edge_size':0.01, 'absolute':True } ]
	else:
		options.local_edge_size =  [ {'face_id':face, 'edge_size':0.015, 'absolute':True } ]
#options.local_edge_size =  [ {'face_id':'wall_right_iliac', 'edge_size':1.0, 'absolute':True } ]

#options.local_edge_size.append( {'face_id':2, 'edge_size':2.0, 'absolute':True } )

## Generate the mesh. 
#
mesher.generate_mesh(options)

mesher.write_mesh()

I get this error (fails on the generate_mesh line of code):

Warning: Parasolid Reports Error in function PK_PART_find_entity_by_ident Error: 5042 PK_ERROR_bad_class_combn
ERROR:  Problem with identifier!
ERROR: LocalEdgeSize: Failed to map ID '13.000' to PID.
Traceback (most recent call last):
  File "<string>", line 49, in <module>
meshing.Error: MeshingMeshSim.generate_mesh() Error setting the '_local_edge_size' option with values '13.000000 1.000000 0.015000 '.

Is there something I'm doing wrong when assigning the local edge size?

**Comment by ktbolt** [comment]
@suhaasa Your code looks fine but it seems that the Parasolid face ID for MeshSim face ID 13 is not recognized by Parasolid. 

Email me your scripts and data and I'll have a look.

**Comment by ktbolt** [comment]
Loading the solid model into the MeshSIm mesher generates errors
```
GAM_numAssemblies(1)
GAM_numParts(2)
Warning: Parasolid Reports Error in function PK_SESSION_ask_curr_partition Error: 5008 PK_ERROR_mark_not_started
Warning: Failure / code : 5008 PK_ERROR_mark_not_started Severity = 1 Entity = 0
Warning: Parasolid Reports Error in function PK_SESSION_ask_curr_partition Error: 5008 PK_ERROR_mark_not_started
Warning: Failure / code : 5008 PK_ERROR_mark_not_started Severity = 1 Entity = 0
```
I don't know what these errors mean. 

I can load the model with no errors using the Modeling module so it seems that MeshSim is doing something that Parasolid does not like.

**Comment by suhaasa** [comment]
Yea, that's pretty odd. I happen to try a model from a different project and it works! I'll try other to see if I can replicate it - otherwise if its just that model, then it might just be corrupted or something.

Also, I was wondering if there is any capability to write the mesh out as a mesh-complete folder for svpre to use? Is there a script that writes out the surface, volume, wall, and each face mesh in the same format?

**Comment by ktbolt** [comment]
The models that you gave are both identified as an assembly of two parts (I'm not sure what that means!). The Parasolid interface only uses a single part if there are more than one. The Parasolid interface code could use a clean up, seems to be a bit kludgy. 

There is currently no capability to write out a mesh-complete folder. I was planning on writing a Simulation module to do that at some point.

**Comment by ktbolt** [comment]
I think the api is working ok.
