### ISSUE TITLE
face extraction does not highlight faces anymore

### ISSUE THREAD

**Issue by baeumler** [SimVascular/SimVascular#772]
**Describe the bug**
When I extract faces from a model (that I imported as stl into SV) there is a face list in the modeling tab. Usually, when clicking on a face name in that list, the face was highlighted in the 3D window, and then I renamed it. Now, the rendering does not make it possible to see anymore which face is highlighted.

**To Reproduce**
1. Go to SV_Modeling tab
2. Click on extract faces
3. click on any face in the face list
4. try to identify face in 3D window

**Expected behavior**
The chosen face used to be highlighted in yellow. Now the chosen face cannot be distinguished from the rest.
![Screen Shot 2020-10-29 at 1 27 49 PM](https://user-images.githubusercontent.com/26555616/97628888-8dfad600-19ea-11eb-8eb8-418a6c063e08.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - SimVascular Version 2020.04.06
 - Medical Image Filetype: stl surface model

**Additional context**

**Comment by ktbolt** [comment]
@baeumler This was a known issue (https://github.com/SimVascular/SimVascular/issues/750) and is fixed for the current SV master branch, you can build a new SV from that.  If you'd like I can build you an installer.

**Comment by baeumler** [comment]
Oh, I did not see that, but good that it is fixed already.

If you could build an installer that would save me a lot of time,
Thanks a lot!

Kathrin
________________________________

**Comment by ktbolt** [comment]
This has been fixed.
