### ISSUE TITLE
Meshing problem

### ISSUE THREAD

**Issue by jche8019** [SimVascular/SimVascular#777]
**Describe the bug**
Not sure if bug or my laptop's processing sucks. 
Been trying to mesh since last night, made sure the mesh doesn't not have multiple caps for vessel. Continuously smoothed wall and created surface mesh prior to meshing. 
However every time  I try it just gets stuck at **Detecting self-intersecting facet**, it's been at it for 75 minute now and Simvas is unresponsive. 
Can anyone confirm if this is normal or should I just cut the operation and try to improve the model further? or could it be some settings I could adjust in meshing?

**Comment by ktbolt** [comment]
@jche8019 Detecting self-intersecting faces should just take a few seconds. How large is your mesh? Upload your model here and I'll have a look.

**Comment by jche8019** [comment]
Thank you so much! 
[Uploading model.zip…]()

**Comment by ktbolt** [comment]
@jche8019 Your mesh did not upload,  maybe too big? Try uploading it somewhere else.

**Comment by jche8019** [comment]
I've solved it through excessive smoothing 👍
