### ISSUE TITLE
Error running simulation

### ISSUE THREAD

**Issue by jche8019** [SimVascular/SimVascular#780]
**Describe the bug**
Non zero exit code 139 

**To Reproduce**
Description of errors, mainly " ERROR opening file [geombc.dat.1]." I reckon

The process ID for myrank (0) is (7715).

The number of processes is 6.

The process ID for myrank (1) is (7717).

The process ID for myrank (2) is (7720).

The process ID for myrank (4) is (7719).

The process ID for myrank (5) is (7718).

Solver Input Files listed as below:
------------------------------------
 Local Config: solver.inp 

The process ID for myrank (3) is (7716).

 Default Input File: Not Setup.

Parameter Values setup as below:
----------------------------------------------
 Time Varying Boundary Conditions From File: True
 BCT File Type: DAT
 Number of BCT Files: 1
 BCT Matching Type: Global Node ID
 BCT Time Scale Factor: 1.0
 Equation of State: Incompressible
 Time Step Size: 0.001
 Number of Timesteps: 1000
 Viscous Control: Viscous
 Number of Timesteps between Restarts: 20
 Print Average Solution: True
 Print Error Indicators: False
 Number of Force Surfaces: 1
 Surface ID's for Force Calculation: 1

 Force Calculation Method: Velocity Based
 Apply Wall Deformation: False
 Number of Surfaces which Output Pressure and Flow: 0

 Density: 1.06

 Viscosity: 0.04
 Solver Type: svLS
 svLS Type: NS
 Number of Krylov Vectors per GMRES Sweep: 100
 Number of Solves per Left-hand-side Formation: 1
 Tolerance on Momentum Equations: 0.01
 Tolerance on Continuity Equations: 0.1
 Tolerance on svLS NS Solver: 0.1
 Maximum Number of Iterations for svLS NS Solver: 10
 Maximum Number of Iterations for svLS Momentum Loop: 10
 Maximum Number of Iterations for svLS Continuity Loop: 400
 Time Integration Rule: Second Order
 Time Integration Rho Infinity: 0.5
 Flow Advection Form: Convective
 Quadrature Rule on Interior: 2
 Quadrature Rule on Boundary: 3
 Number of Elements Per Block: 255
 Number of Coupled Surfaces: 6
 Pressure Coupling: Implicit
 Number of Resistance Surfaces: 6
 List of Resistance Surfaces: 2 3 4 6 7 8
 Resistance Values: 1800 1800 1800 1800 1800 1800
 Backflow Stabilization Coefficient: 0.2
 Deformable Wall: False
 Residual Control: True
 Residual Criteria: 0.001
 Minimum Required Iterations: 3
 Step Construction: 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 Solver Task: Full Simulation

Directory 6-procs_case/ already exists 
 Using the existing inputfiles
Changed to the directory 6-procs_case/

ERROR opening file [geombc.dat.1].
ERROR opening file [geombc.dat.3].
ERROR opening file [restart.0.3].
ERROR opening file [geombc.dat.4].
ERROR opening file [restart.0.4].
ERROR opening file [restart.0.1].
ERROR opening file [geombc.dat.5].
ERROR opening file [restart.0.5].
ERROR opening file [geombc.dat.6].
ERROR opening file [restart.0.6].
ERROR opening file [geombc.dat.2].
ERROR opening file [restart.0.2].
/usr/local/sv/svsolver/2019-02-07/svsolver: line 58:  7718 Segmentation fault      (core dumped) $SV_HOME/bin/svsolver $*

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - SimVascular Version [2020]
 - Medical Image Filetype [dcm]

**Additional context**

**Comment by Silas-medimg** [comment]
excuse me. I'm facing the similar issue. How did you solve this question ERROR opening file [geombc.dat.1]?
