### ISSUE TITLE
Generate 1D models "from scratch"

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#781]
Currently, we have a pipeline to create 1D models from existing 3D models. However, it would be very useful to generate 1D models without having a 3D model.

Since 1D models are very fast to compute, this pipeline could be a valuable tool for users starting with a new project. If we had a "paint-like" user interface where users can "draw" a 1D vessel network, you could sketch up and run a 1D model within minutes. The only information we need is the length, cross-sectional area, and connectivity of vessel branches.

I have two ideas on how to do that (and didn't spare any expense to visualize them):
1. Sketch a 2D vessel and do a "2D centerline-extraction"
<img width="250" alt="Screen Shot 2020-11-16 at 10 57 10 AM" src="https://user-images.githubusercontent.com/51269309/99295924-db54b100-27fa-11eb-8e6f-cdcbec52c7c8.png">
2. Directly draw the vessels as lines in a 2D plane and edit the cross-sectional area via the thickness of the lines.
<img width="215" alt="Screen Shot 2020-11-16 at 10 59 12 AM" src="https://user-images.githubusercontent.com/51269309/99295938-e0b1fb80-27fa-11eb-955a-93a6f89e1f9e.png">

@ktbolt Do you think this is feasible in SimVascular?

**Comment by ktbolt** [comment]
@mrp089 I think this would be possible in SV. We have a similar plan for generating 0-D models by displaying a 2D model editing window separate from the SV 3D window, snap input nodes to grid points displayed in the window.

Note that 1D models can also be created from the colliding fronts segmentation tool which automatically creates centerlines from the segmentation surface.

Are there plans for creating 1D models using the Path planning tool?

**Comment by RAJA2093** [comment]
@ktbolt  Currently, is it possible to generate 1D model directly in simvascular without using 3D model?

**Comment by ktbolt** [comment]
@RAJA2093 You just need import into the SV Modeling the 3D surface model of the anatomy you want to simulate. The ROMSimulation tool will then extract centerlines from that model and use them in the 1D simulation.

**Comment by RAJA2093** [comment]
@ktbolt  Thank you so much for your response. Yes, with the 3D model of anatomy, I can create a 1D simulation. But currently, I don't have a 3D model of the anatomy of the vessels. Instead, I have the details of the arterial tree such as diameter, cross-sectional area, length, Young's modulus, nodes, joints, inlets, outlets, etc. Can I create a 1D simulation in sim vascular without a 3D model with these details?

**Comment by ktbolt** [comment]
@RAJA2093 Please post these questions in the SimVascular Forum.

**Comment by RAJA2093** [comment]
yeah. sure. Thanks.
