### ISSUE TITLE
Faces are not highlighted on model

### ISSUE THREAD

**Issue by melodydong** [SimVascular/SimVascular#784]
On Ubuntu 18, the 2020-09-21 version of SimVascular does not highlight the face when in Models tab. 

The model is automatically colored red when created and the yellow highlight when a face (cap or wall) is selected in the Models tab does not show or shows very faintly through the red colored model. Only when I remesh the model, will the model be colored white and then the faces are shown highlighted in bright yellow.

**Comment by ktbolt** [comment]
@melodydong I think this is fixed in https://github.com/SimVascular/SimVascular/issues/750. 

I'll build an installer from the latest master branch. See if that works.

**Comment by ktbolt** [comment]
It works!
