### ISSUE TITLE
1d modeling: Add Python packages for adaptive meshing

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#796]
The 1D pipeline includes an option to adaptively place segments in areas of high change in cross-sectional area (#578). This function uses the package [pwlf](https://pypi.org/project/pwlf/) which uses the package [pyDOE](https://pythonhosted.org/pyDOE/). They should be included in the ```site-packages``` folder.

**Comment by ktbolt** [comment]
@mrp089 So pyDOE needs scipy, no simple workaround for that, maybe you were picking up scipy from your path.

If mesh adaptivity is important then we could add a try/except around `import scipy` and disable adaptivity if scipy is not available. I assume that the scipy package can be loaded outside of SV.

**Comment by mrp089** [comment]
I wrapped ```import pwlf``` in a ```try: ... except ImportError:``` statement and turn off adaptive meshing if it can't be loaded.
