### ISSUE TITLE
Python API: ML segmentation

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#804]
It would be great if we could do machine learning segmentation from the Python API. As discussed with @ktbolt, "the interface just takes a path to an image and a coordinate frame defining a plane, returns a list of points defining the segmentation."

Needed for @numisveinsson.

**Comment by ktbolt** [comment]
I will need to think about how to add image reading and slice extraction to the API. I've already prototyped this but want to decide if most of the image functionality should be outside of the API using VTK or ITK.

**Comment by mrp089** [comment]
The image reading and slicing can be done using the ML plugin as a standalone (see [documentation](https://github.com/SimVascular/SimVascular/blob/master/Python/site-packages/sv_ml/README.md)). Thus, we don't need access through the Python API for now.
