### ISSUE TITLE
SV 1D Simulation plugin opens in new window

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#816]
**Describe the bug**
When I create a new 1D simulation job and double-click on it, the SV 1D Simulation plugin opens in a new window (instead of the plugin toolbar).

**To Reproduce**
1. Right-click Simulations1d -> Create 1D Simulation job
2. Enter Job Name
3. Double-click job name

**Expected behavior**
The SV 1D Simulation plugin should be included in the toolbar on the right.

**Screenshots**
![Screen Shot 2021-02-22 at 11 34 06 AM](https://user-images.githubusercontent.com/51269309/108760124-1a815500-7502-11eb-98e7-b6ae59237e35.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 11.2.1 Big Sur
 - SimVascular 2021.02.06 and 2020.04.06

**Comment by ktbolt** [comment]
@mrp089 I have not been able to reproduce this on my MacOS 10.13. I am thinking this is caused by the five other tools already open. 

Removing the SV database files in **~/Library/Application Support/SimVascular** should return the 1D tool to its normal place.

**Comment by mrp089** [comment]
Thanks, @ktbolt, deleting the files did the trick!
