### ISSUE TITLE
1D post-processing

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#817]
Add more post-processing for svOneDSolver results:
- export results as numpy arrays (sorted by branches)
- project results to centerline
- project results to volume mesh

I'll add the code to ```sv_1d_extract_results``` and execute the post-processing (for now) in ```Convert Results``` -> ```Convert...```

@ktbolt, can you pass the following parameters from the GUI to Python (variable ```params``` of function ```run``` in file ```extract_results.py```):
- [ ] ```mesh_vol```: path to volume mesh
- [ ] ```mesh_wall```: path to **wall** mesh (```walls_combined.vtp```)
- [ ] ```centerline```: filename centerline (```centerlines.vtp```)
- [ ] ```oned_model```: filename 1D geometry (```1d_model.vtp```)

Thanks!

**Comment by ktbolt** [comment]
@mrp089 I will need to add widgets to the **Convert Results** panel 

1. Export results as numpy arrays - Check box
2. Project results to centerline - Check box
3. Project results to volume mesh - Combo box containing the names of Simulation jobs

Option 3 will be the most work.

**Comment by ktbolt** [comment]
I've added the widgets to the GUI and added code to process the new parameters. 

<img width="480" alt="Screen Shot 2021-03-24 at 9 51 17 PM" src="https://user-images.githubusercontent.com/23109458/112420996-7d296480-8ceb-11eb-9fa9-2cb0824c1ebd.png">

It took most of a day just to do this, so many things need to be added to read/write the `.s1djb` file, set GUI state, etc. I still need to add passing these new parameters to Python.

**Comment by ktbolt** [comment]
I've added passing the new parameters to the Python script
```
[18.663] [sv4guiSimulationPythonConvert1d::ConvertResults] Execute script ...
{ 'centerlines_file': '/Users/parkerda/SimVascular/sim-1d-demo-new/Simulations1d/demo/centerlines.vtp',  
 'walls_mesh_file': '/Users/parkerda/SimVascular/sim-1d-demo-new/Simulations/sim-1/mesh-complete/walls_combined.vtp', 
'volume_mesh_file': '/Users/parkerda/SimVascular/sim-1d-demo-new/Simulations/sim-1/mesh-complete/mesh-complete.mesh.vtu'
```

@mrp089 What is the `oned_model` parameter? And should `Export results as numpy arrays` just be a value set for the `output_format` parameter?

**Comment by ktbolt** [comment]
@mrp089 I will need to merge this code before I start on https://github.com/SimVascular/SimVascular/issues/815. Shall I do that?

**Comment by mrp089** [comment]
Yes!

**Comment by ktbolt** [comment]
Merge into master.

**Comment by mrp089** [comment]
@ktbolt I started connecting my code with the GUI following #830. You mentioned there's more to do, so this might be redundant.

Currently, the parameters ```walls_mesh_file``` and ```volume_mesh_file``` and the three checkboxes are not being passed to Python. In my example, the parameters I get are
```
{'output_directory': '/home/pfaller/work/osmsc/data_generated/svprojects/0075_1001/oned/converted/oned-converted-results',
'results_directory': '/home/pfaller/work/osmsc/data_generated/svprojects/0075_1001/oned',
'centerlines_file': '/home/pfaller/work/osmsc/data_generated/svprojects/0075_1001//oned/centerlines.vtp',
'data_names': 'area,flow,pressure,Re',
'solver_file_name': 'solver.in',
'output_file_name': 'oned',
'all_segments': 'true',
'time_range': '0.0,0.3'}
```


Also, when I generate a mesh and then open the 1D plugin SimVascular crashes with a ```std::exception```.

**Comment by ktbolt** [comment]
@mrp089 I just merged into master a fix to check for no convert props in an .s1djb file, this was causing SV to crash when opening the 1D plugin with an old .s1djb file. 

I also added code to check that there are simulations matching the model used by the 1D plugin.

Try the new SV master and see if it works for you. If it doesn't then send me a link to your project.

**Comment by mrp089** [comment]
Thanks, @ktbolt, that fixed the crash for me.

I created #833 to connect the GUI to the Python post-processing functions.

I noticed that  ```centerlines_file```, ```walls_mesh_file```, and ```volume_mesh_file``` are only passed when the corresponding options in the GUI are selected. However, there's a dependency: ```Project results to 3D mesh``` also needs  ```centerlines_file``` because the order of projection is ```1D -> centerline -> 3D```. So if a user only checks ```Project results to 3D mesh```, I don't know the location of the centerline.

In addition, I currently can't check if the option ```Write results as NumPy arrays``` is selected in the GUI (for now, I always execute that step).

@ktbolt Is it possible to always pass all paths and the status of the checkboxes separately?

The easy way around this would be to just always execute all three post-processing options. The only time-consuming step is the ```centerline -> 3D``` projection. However, I think it's good to have all three checkboxes in the GUI so users know these outputs exist.

**Comment by ktbolt** [comment]
@mrp089 I can add passing centerlines if `ProjectTo3DMesh` is checked. 

I'm not yet passing the `Write results as NumPy arrays` because I didn't know what to send, was wondering if I should set a value set for the output_format parameter or create a new bool parameter.

**Comment by ktbolt** [comment]
I've added sending a centerlines file when `ProjectTo3DMesh` is checked.

<img width="495" alt="Screen Shot 2021-04-09 at 12 17 37 PM" src="https://user-images.githubusercontent.com/23109458/114230269-cd303a00-992d-11eb-86c8-7f605f59ae60.png">


```
Execute script ...
{'output_directory': 'sim-1d-demo-new/Simulations1d/demo/demo-converted-results', 
'outlet_segments': 'true', 
'walls_mesh_file': 'sim-1d-demo-new/Simulations/sim-1/mesh-complete/walls_combined.vtp', 
'data_names': 'area,flow',
 'output_file_name': 'demo', 
'solver_file_name': 'solver.in', 
'centerlines_file': 'sim-1d-demo-new/Simulations1d/demo/centerlines.vtp', 
'results_directory': 'sim-1d-demo-new/Simulations1d/demo', 
'time_range': '0.0,2.001', 
'volume_mesh_file': 'sim-1d-demo-new/Simulations/sim-1/mesh-complete/mesh-complete.mesh.vtu'}
```

**Comment by mrp089** [comment]
Thanks, @ktbolt! I'm closing this. I will add more post-processing once we have integrated the 0D modeling #815

**Comment by mrp089** [comment]
@ktbolt When someone hits the ```Convert ...``` button, can you also pass ```model_order```? Thanks!
