### ISSUE TITLE
Green horizontal lines

### ISSUE THREAD

**Issue by maraboump** [SimVascular/SimVascular#823]
I installed SimVascular a few days ago and when I open the screen is full of horizontal green lines which makes it impossible to work. Don't have this issue with any other software. Any idea why? Thanks!
![simvascular](https://user-images.githubusercontent.com/80896345/111623328-264ef700-87e2-11eb-9b72-b14107ee1f58.jpg)

**Comment by ktbolt** [comment]
@maraboump This is probably caused by an outdated graphics driver. See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=188&t=12559&p=35799&start=0&view=.

**Comment by maraboump** [comment]
Hello, 

Thank you very much for the reply. 

I had a look at the post and maybe the issue comes from the 2 GPUs, Intel and Nvidia, in my case as well. I will try the steps from the link provided there, and hopefully it will be resolved!

**Comment by ktbolt** [comment]
@maraboump From what I've seen this is indeed that problem. Please post to the SV Forum if you have further problems, good for other users to see this.
