### ISSUE TITLE
non-zero exit code - 1073741819

### ISSUE THREAD

**Issue by gabiiealmeida** [SimVascular/SimVascular#829]
Hello, so basically I can't simulate my project because when I do 'Run Simulation' I always get this error. Can anyone help me?

**Comment by ktbolt** [comment]
@gabiiealmeida Please repost in the SV Forum so other users can see this. Also include what platform you are running on, which solver you are using and any information printed out in the SV console window.

**Comment by ktbolt** [comment]
@gabiiealmeida You should also include what is printed the popup window after selected the `Show Details` button.
