### ISSUE TITLE
Issues compiling SimVascular from source

### ISSUE THREAD

**Issue by JonathanPham** [SimVascular/SimVascular#846]
I am trying to compile SimVascular from source on my Ubuntu 20.04.2 LTS. I used the following commands to compile:

```
cd SimVascular
mkdir build
cd build
cmake ..
make
```

However, I get many warning messages at the beginning of the compilation stage, such as

```
CMake Warning at /home/jonathanpham/Documents/software/SimVascular/SimVascular/Code/CMake/SimVascularMacros.cmake:1510 (message):
  Pre-built binaries for the operating system and compiler do not exist! The
  best possible match will be downloaded; however, problems may occur,
  especially if the pre-built binaries are compiled with a different
  compiler.  Pre-built binaries for ubuntu version 16.04 and compiler gnu-5.4
  are being downloaded and used.  Proceed with caution!
Call Stack (most recent call first):
  /home/jonathanpham/Documents/software/SimVascular/SimVascular/Code/CMake/SimVascularMacros.cmake:1375 (sv_externals_check_versioning)
  CMake/SvExtOptions.cmake:79 (sv_externals_add_new_external)
  CMakeLists.txt:83 (include)
```

After the warning messages, the program proceeds to download various packages and compile, but finally, the compilation stage ends with the following failure message.

```
cmake -E tar: warning: unknown warning
CMake Error: Problem with archive_write_header(): Can't create 'qt-5.11.3/Docs/Qt-5.11.3/qtwidgets/images/widget-examples.png'
CMake Error: Current file: qt-5.11.3/Docs/Qt-5.11.3/qtwidgets/images/widget-examples.png
CMake Error: Problem extracting tar: /home/jonathanpham/Documents/software/SimVascular/SimVascular/build/Externals-build/svExternals/prefix/qt-5.11.3/src/ubuntu.16.04.gnu.5.4.x64.release.2019.07.14.qt.5.11.3.tar.gz
-- extracting... [error clean up]
CMake Error at /home/jonathanpham/Documents/software/SimVascular/SimVascular/build/Externals-build/svExternals/prefix/qt-5.11.3/src/QT-stamp/extract-QT.cmake:33 (message):
  error: extract of
  '/home/jonathanpham/Documents/software/SimVascular/SimVascular/build/Externals-build/svExternals/prefix/qt-5.11.3/src/ubuntu.16.04.gnu.5.4.x64.release.2019.07.14.qt.5.11.3.tar.gz'
  failed


make[5]: *** [CMakeFiles/QT.dir/build.make:93: svExternals/prefix/qt-5.11.3/src/QT-stamp/QT-download] Error 1
make[4]: *** [CMakeFiles/Makefile2:203: CMakeFiles/QT.dir/all] Error 2
make[3]: *** [Makefile:130: all] Error 2
make[2]: *** [CMakeFiles/Externals.dir/build.make:112: Externals-prefix/src/Externals-stamp/Externals-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/Externals.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

It looks like maybe the program is trying to use some ubuntu.16.04 packages to compile, even though I am using a Ubuntu 20.04.2 LTS workstation. Do you have any ideas on how to resolve these issues?

**Comment by ktbolt** [comment]
@JonathanPham The issue you are seeing seems to be caused by not being able to untar the externals, not sure why this is, are you out of disk space? Please include the entire build output.

What version of gcc is installed? It seems that you have an older gcc version for Ubuntu 16.

**Comment by JonathanPham** [comment]
@ktbolt Turns out I was running out of disk space. I fixed that issue and tried to re-build SimVascular. However, the build process failed again, but with different error messages. The entire build output is included in the attached text file.

My computer is using gcc version 7.5.0. 
[simvascular_build_failure_2021_04_26.txt](https://github.com/SimVascular/SimVascular/files/6381620/simvascular_build_failure_2021_04_26.txt)

**Comment by ktbolt** [comment]
The `undefined reference to non-virtual thunk to mitk::BaseData::GetPropertyContextNames[abi:cxx11]() const'
` error is caused by a mismatch in gcc versions.

I see in the CMake log file
```
Pre-built binaries for ubuntu version 16.04 and compiler gnu-5.4
  are being downloaded and used.
```
so you are trying to use a gcc 5 version of the externals.

The externals version is determined from the file http://simvascular.stanford.edu/downloads/public/simvascular/externals/2019.06/linux/ubuntu/externals_compiler_info.txt
```
16.04/gnu/5.4/x64/release/2019.07.14
16.04/gnu/5.4/x64/relwithdebinfo/2019.07.16
18.04/gnu/7.3/x64/release/2021.02.01
19.04/gnu/8.3/x64/release/2019.07.22
```
using the `sv_externals_check_versioning` macro defined in`SimVascular/Code/CMake/SimVascularMacros.cmake`.  The macro has determined that `compiler_type_only` was found, gcc I guess, not sure why. I would think that matching the compiler version would give you the best match, although there could still be library names mismatch.

I don't know how to fix this, maybe you could hard-code the values in `sv_externals_check_versioning` to give you the `18.04/gnu/7.3/x64/release/2021.02.01` externals.

**Comment by osmsc** [comment]
@JonathanPham & @ktbolt - the externals pulls as the default the top distribution from the file.  I tried bumping up 18.04 to be above 16.04.  Do you want to see if this works the problem.  I will try and build the externals on ubuntu 20.04 sometime soon so we have a native build for it.

**Comment by ktbolt** [comment]
@osmsc The externals are still being set to 16.04 and compiler gnu-5.4, appears to look at all of the versions in the file.

**Comment by JonathanPham** [comment]
@osmsc and @ktbolt The file, http://simvascular.stanford.edu/downloads/public/simvascular/externals/2019.06/linux/ubuntu/externals_compiler_info.txt, has the following contents:

```
16.04/gnu/5.4/x64/release/2019.07.14
16.04/gnu/5.4/x64/relwithdebinfo/2019.07.16
18.04/gnu/7.3/x64/release/2021.02.01
19.04/gnu/8.3/x64/release/2019.07.22
```

Since there is no 20.04 version listed in this file, does this mean that the SimVascular source code is not compatible with Ubuntu 20.04.2 LTS? 

Or do I need to update my system somehow so that the correct version of the externals is used?

**Comment by ktbolt** [comment]
No 20.04 version in this file means that the externals have not been explicitly build for Ubuntu 20.04 with it's default GCC 9.3.0 compiler. The SimVascular source code should not have a problem compiling on Ubuntu 20.4.

You could probably build OK with the `18.04/gnu/7.3/x64/release/2021.02.01` externals if you could get CMake to download them. You could try installing GCC 7.3, maybe CMake would then choose the `18.04/gnu/7.3/x64/release/2021.02.01` externals. Before doing that you should check that the libraries used by Ubuntu 18 are compatible with 20.04 (e.g.  **libssl**  is a typical incompatibility between Ubuntu  releases).

**Comment by JonathanPham** [comment]
I think the recent update and pull request (#884) fixed the build/compile issue for me. Thanks @ktbolt  and @osmsc!
