### ISSUE TITLE
Run 0D simulations from the GUI

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#854]
Currently, 1D simulations can be run from the GUI within the ROM plugin. However, this is currently not possible for the 0D solver. This can be done with a simple Python call to https://github.com/SimVascular/svZeroDSolver/blob/master/run_0d_solver_fast.py with the solver input file as its argument. Requires #853 (add 0D solver code to SimVascular)

**Comment by ktbolt** [comment]
I've added code to execute the `svZeroDSolver` from the SV GUI but there are some problems with the `svZeroDSolver` Python code that need to be fixed

1) There is no `__intit__.py` file so `svZeroDSolver`  is not treated as a package, also need relative paths in import statements.

2) It tries to import packages that are not supported in SV (e.g.`iqdm`).

3) There is a `svZeroDSolver.py` file, same name as the package, sort of confusing.

4) The `svZeroDSolver.py` script can only be executed from the command line, it can't be called from C++.

@mrp089 @JonathanPham Shall I make the necessary code changes? i don't think I will mess things up too much ...

**Comment by mrp089** [comment]
@ktbolt OK for me if you make these changes, but happy to support if you want to

**Comment by ktbolt** [comment]
I will have at it then, should not be too much work. Do we need to pass any arguments besides the solver file name to `svZeroDSolver.py`?

**Comment by mrp089** [comment]
Nope! We put everything necessary in the input file and use default values for other parameters

**Comment by ktbolt** [comment]
I've reorganized `svZeroDSolver.py` and added a `run_from_c(*args, **kwargs)` function that can now be called from C++. This seems to work
```
Number of unknowns =  14
Number of equations =  14
starting simulation
0D simulation completed!
```

I needed to modify the `__intit__.py` file and some other .py files to enable using the `svZeroDSolver` package in SV Python/site-packages. However, these changes prevent calling `svZeroDSolver.py` directly from the git repo.

@JonathanPham  There is no `setup.py` script in the svZeroDSolver repo. How do you envision people using the package?

**Comment by JonathanPham** [comment]
@ktbolt, I am not sure what a `setup.py` script is. I've never seen it before. 

However, we were thinking that users could run the 0D solver from the SimVascular GUI, stand-alone, or both (similar to how users could run the 1D/3D solver from the SimVascular GUI or stand-alone).

**Comment by ktbolt** [comment]
A `setup.py` file is used to install a Python package in ` /usr/local/lib/python/site-packages`. Running `python setup.py install` would add the `svZeroDSolver` package  so a user could run it stand alone. 

Let me think about how to package `svZeroDSolver` .

**Comment by JonathanPham** [comment]
Thanks for the explanation, @ktbolt! Let me know if there is anything I can do to help.

**Comment by ktbolt** [comment]
I've opened an Issue for converting the code into a Python package (see https://github.com/SimVascular/svZeroDSolver/issues/30).

I will need to update the SV code when 0D solver code is reorganized.

**Comment by ktbolt** [comment]
Merged.
