### ISSUE TITLE
Polydata Cap Remeshing

### ISSUE THREAD

**Issue by zasexton** [SimVascular/SimVascular#862]
**Is your feature request related to a problem? Please describe.**
For solid generation in the Python API pipeline the cap faces that are initially generated with vmtk need to be remeshed before these models can be meshed (otherwise meshing terminates with errors). 

**Describe the solution you'd like**
Either 1) an additional method for the modeling.PolyData() solid objects class that specifically remeshes the identified caps in-place or 
2) another method in the mesh_utils module that accepts a solid model and then recognizes the caps and remeshes them;  returning the resulting polydata

**Describe alternatives you've considered**
Currently I've been breaking up the solid models by faces and remeshing the caps using the mesh_utils.remesh() method; however I then need to reconstruct the polydata for the solid and ensure that there are no free edges using vtkAppendPolyData and vtkFeatureEdges. Even when I do this there are problems that arise with Unioning these solids (this can be seen with the missing cells in the attached image)

**Additional context**
![Polydata_remeshing_union_error](https://user-images.githubusercontent.com/47196674/119052126-f73b3a00-b978-11eb-998a-3defb597b5b8.png)

**Comment by ktbolt** [comment]
@zasexton The SV GUI supports face remeshing. Let me look through the code to see how that's done.

The SV PolyData Boolean operations are not very robust, you will probably need to adjust the mesh refinement until it works.

**Comment by zasexton** [comment]
I have been readjusting the remeshing; however it really only works well for the walls. The caps still have a few issues so my current work around has been to break the models up, remesh the components and then combine the faces before unioning. (It’s worked okay-ish)

—
Stanford Bioengineering
NSF Graduate Fellow
________________________________

**Comment by ktbolt** [comment]
I've added a `sv.mesh_utils.remesh_faces()` method to the Python API that can remesh selected faces like this
```
kernel = sv.modeling.Kernel.POLYDATA
modeler = sv.modeling.Modeler(kernel)
model = modeler.cylinder(center=center, axis=axis, radius=radius, length=length)
model_pd = model.get_polydata()
face_ids = [3]
remeshed_model = sv.mesh_utils.remesh_faces(model_pd, face_ids, edge_size=msize)
```
The image shows the original polydata (green lines), the remeshed polydata (white lines) and the fe mesh (red with black lines)

![Screen Shot 2021-05-20 at 10 45 37 PM](https://user-images.githubusercontent.com/23109458/119088204-22e01380-b9bd-11eb-9dc2-d432650e60ae.png)

Share some models with me and I will test.

**Comment by zasexton** [comment]
This looks amazing! I've sent along a non-remeshed model to test as well

**Comment by ktbolt** [comment]
I tried the face remeshing on the model you sent me, seemed to work ok
![Screen Shot 2021-05-21 at 11 26 38 AM](https://user-images.githubusercontent.com/23109458/119184437-3aa1b100-ba2a-11eb-80d7-7ddd642f2c6e.png)

Note that you need to be careful with the TetGen mesher `global_edge_size`. The mesher first remeshes the input model surface using `global_edge_size`. If it is too large then you can get a non-manifold error from the mesher, not sure what's going on with that. 

So I think you should use the same or smaller value for `global_edge_size` as used for the `sv.mesh_utils.remesh_faces()` `edge_size` like this
```
remeshed_model = sv.mesh_utils.remesh_faces(model_pd, face_ids, edge_size=msize)

options = sv.meshing.TetGenOptions(global_edge_size=msize, surface_mesh_flag=True, volume_mesh_flag=True)
```

**Comment by zasexton** [comment]
I'll keep the edge size in mind as I build the models and meshes. I did notice that if there are any differences in mesh resolution that the remeshing will crash. Is there a repository I should build from to test out the face remeshing?

**Comment by ktbolt** [comment]
I've merged the changes into SV master. 

The script I used to test is here https://github.com/SimVascular/SimVascular-Tests/blob/master/new-api-tests/modeling/remesh-faces.py

**Comment by zasexton** [comment]
Thanks! I built it and it's working great.
