### ISSUE TITLE
Add reading legacy path and contour files to the Python API.

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/SimVascular#873]
We would like to be able to read  legacy path and contour files using the Python API.

**Comment by ktbolt** [comment]
I've add reading legacy paths
```
# Read file from constructor.
paths = sv.pathplanning.Series(file_name, legacy=True)
```

or 

```
# Read file from object. 
paths = sv.pathplanning.Series()
paths.read(file_name, legacy=True)
```

This required reorganizing `Code/Source/sv4gui/Modules/Path/sv4gui_PathLegacyIO.cxx` code because it uses pure Qt to parse the `.paths` file and is very different from the way `sv3` code is used to parse XML path files.

Note that the Python API can only read in `.paths` files that contain a single path.

**Comment by ktbolt** [comment]
@osmsc Do the legacy path files you have contain multiple paths?

**Comment by osmsc** [comment]
@ktbolt - yes, they contain multiple paths but I could write a Tcl script to separate each path into an independent file and then call the conversion code.  So having code that converts one path at a time is still useful.

**Comment by ktbolt** [comment]
@osmsc I've added the `pathplanning.Series.read_legacy` class method that can read in a paths file containing multiple paths. It returns a list of `sv.pathplanning.Series` objects
```
# Read path files using a class method. 
path_series_list = sv.pathplanning.Series.read_legacy(file_name)
print("Number of path series read: {0:d}".format(len(path_series_list)))

for path_series in path_series_list:
    print("----------  Name: {0:s} ----------".format(path_series.get_name()))
    print("  Number of time steps: {0:d}".format(path_series.get_num_times()))
    print("  Path at time 0:")
    path = path_series.get_path(0)
    control_points = path.get_control_points()
    print("  Number of control points: {0:d}".format(len(control_points)))
```

The name of the path_series is read from the .paths file.

**Comment by ktbolt** [comment]
I've added reading legacy contour files. I also added `read()` and `write()` methods.
```
file_name = str(data_path / 'segmentation' / '0110_0001_groups-cm' / 'aorta')
# Bad file name to test error handling.
#file_name = str(data_path / 'segmentation' / '0110_0001_groups-cm' / 'aorta1')
print("Read SV legacy files: {0:s}".format(file_name))

# Read an SV segmentation group file from the contructor. 
if False:
    seg_series = sv.segmentation.Series(file_name, legacy=True)

# Read an SV segmentation group file using the 'read()' method.
else:
    seg_series = sv.segmentation.Series()
    seg_series.read(file_name, legacy=True)

num_times = seg_series.get_num_times()
print("Number of time points: {0:d}".format(num_times))

# Write the segmentation series to a file.
seg_series.write(str(script_path / "test-aorta-legacy.ctgr"))
```

I spent a lot of time figuring out some subtle problems using `sv4guiContourGroup::Pointer` in the Python API, had `sv4guiContourGroup` objects calling their destructor right after they were created.

**Comment by ktbolt** [comment]
@osmsc I've created test scripts in `SimVascular-Tests/new-api-tests/`
```
segmentation/read-legacy-series.py

pathplanning/read-legacy-multiple-paths-file.py	
pathplanning/read-legacy-paths-file.py
```

The code is in https://github.com/ktbolt/SimVascular/tree/Reading-legacy-path-contour-files-Python-API_873.
