### ISSUE TITLE
ROM: Centerline not saved

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#907]
**Describe the bug**
When creating a new ROM simulation, the centerline doesn't get saved. This causes `Create Files for Simulation` to fail.

**To Reproduce**
1. Open existing SimVascular project
2. Create new ROMSimulation `test`
3. Select inlet face, click `Calculate Centerlines`
4. (Default `Basic Parameters`)
4. Enter `Inlet and Outlet BCs`
5. (Default `Wall Properties`)
5. Enter `Solver Parameters`
6. Click `Create Files for Simulation`

Fails with:
 `[generate-1d-mesh] ERROR - The centerlines input file '[...]/ROMSimulations/test/centerlines.vtp' was not found.`

To successfully run a simulation, the following steps are necessary:
1. Click `Create Files for Simulation` (crashes, but creates folder  '[...]/ROMSimulations/test/`)
2. Click `Calculate Centerlines`
3. Click `Create Files for Simulation`

**Expected behavior**
The centerlines should be saved to `ROMSimulations/test/centerlines.vtp` after they're calculated. However, the folder `ROMSimulations/test` is only created when clicking `Create Files for Simulation`. Thus, there's no folder to save the centerlines.

**Desktop:**
 - OS: Ubuntu 18.04 LTS
 - SimVascular Version 2021.06.15
 - [Sample SimVascular project](https://drive.google.com/file/d/1rw3O5YyM8WdHxOvsUnsSjCyQOZ81Z0r2/view?usp=sharing)

**Comment by ktbolt** [comment]
What was the `existing SimVascular project` ? 

Did the `ROMSimulations` exist?

**Comment by mrp089** [comment]
Fixed by 43afb77
