### ISSUE TITLE
ROM: Centerline needs to be recomputed when opening project

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#908]
**Describe the bug**
When opening a SimVascular project with a ROMSimulation and existing centerline, the centerline is not recognized. It appears in the sidebar, but the button `Create Files for Simulation` is grayed out. Recomputing the centerline via `Select Inlet Face` and `Calculate Centerline` enables `Create Files for Simulation`.

**To Reproduce**
1. Open [SimVascular project](https://drive.google.com/file/d/15JUW7G_F8bmVdNwj4pKjbSUTQ-ITjiLr/view?usp=sharing)
2. Open ROMSimulation `rom`
3. Try to click `Create Files for Simulation`

`Create Files for Simulation` is grayed out even though all necessary files are in `ROMSimulations/rom`

**Expected behavior**
SimVascular should be aware of existing files and allow users to directly create the simulation files without recomputing the centerline (which can take a while in large models).

**Desktop**
 - OS: Ubuntu 18.04 LTS
 - SimVascular Version 2021.06.15

**Comment by ktbolt** [comment]
Did this used to work or is it something you just noticed?

**Comment by mrp089** [comment]
Not sure... I only discovered it when preparing for the workshops while opening and closing projects repeatedly.

**Comment by ktbolt** [comment]
@mrp089 What project were you using? For old projects (e.g. Demo Project) on SimTK there is no `Simulations1d` directory.  If `Simulations1d` exists then SV renames it to `ROMSimulations`, if it doesn't then it did not create the `ROMSimulations` dir, I just fixed that.

**Comment by ktbolt** [comment]
I just tested on Ubuntu and Mac, worked fine.

**Comment by mrp089** [comment]
That's what it looks like for me:

https://user-images.githubusercontent.com/51269309/123737007-13bf7180-d857-11eb-95ba-b11f9714022d.mov

**Comment by ktbolt** [comment]
It seems that SV is not reading in the ROMSimulation parameters correctly, no inlet face is selected. 

Your ROM job is outside of the ROMSimulations dir?

<img width="835" alt="Screen Shot 2021-06-28 at 9 27 06 PM" src="https://user-images.githubusercontent.com/23109458/123737513-eaebac00-d857-11eb-9b78-4b1c11e6eb8e.png">

Let's Zoom tomorrow and figure this out.

**Comment by mrp089** [comment]
Fixed with 43afb77
