### ISSUE TITLE
ROM: Convert results log output repeated

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#909]
**Describe the bug**
Log output is duplicated `n` times when running `ROMSimulations -> Convert Resutls -> Convert ...` for the `n`-th time.

**To Reproduce**
1. Open [SimVascular project](https://drive.google.com/file/d/1Pt_8cD011gsujTAwYqvpOq1Lx5_6wQo0/view?usp=sharing)
2. Navigate to `Convert Results` and enter path `[...]/ROMSimulations/rom` for `Results Directory` and `Convert Directory`
3. Click `Convert ...`
4. Click `Convert ...` again
5. Click `Convert ...` again

Every line in the log output is repeated three times.

**Expected behavior**
Log output shouldn't change in each run.

**Screenshots**
![image](https://user-images.githubusercontent.com/51269309/123719558-b9161d80-d836-11eb-91c7-54d757a7cad4.png)

**Desktop (please complete the following information):**
 - OS:Ubuntu 18.04 LTS
 - SimVascular Version 2021.06.15

**Comment by ktbolt** [comment]
I've fixed this in #938, was creating a new logger handler every time the module was loaded.
