### ISSUE TITLE
ROM: Default to 0D

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#913]
Currently, the 0D solver is faster and, crucially, more robust than the 1D solver. When compared to 3D, the 0D results at the caps are a tiny bit worse than 1D. The 0D results become much better (and robust) than 1D once stenosis modeling (#841) is included. I think we should default to 0D in the `ROMSimulations` plugin for a better user experience.

**Comment by ktbolt** [comment]
I've changed the GUI so that the 0D solver is default, merged into master.
