### ISSUE TITLE
how to simulation with vessel stl file

### ISSUE THREAD

**Issue by junqiangchen** [SimVascular/SimVascular#932]
hi,
i have stl vessel model,so i load the stl into Models,and convert into mesh,next simulation the result,but the error is Please make sure the mesh exists and is valid?
can you help me how to do it?is there any video tutorials?
![image](https://user-images.githubusercontent.com/28638716/131978691-2f44ccca-b65d-4715-a8a4-ddccab85ef3a.png)

thank you

**Comment by ktbolt** [comment]
@junqiangchen Please post this question in the SV Forum so other users can see it.
