### ISSUE TITLE
Missing libmpi.so.20 library on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by andre-mourato-61459** [SimVascular/SimVascular#933]
Hey everyone, i hope this post finds you all well and safe.

So i was trying to use the mpiexe to run a simulation of aTAA on SimVascular but the following message always appear:

![Screenshot from 2021-09-09 12-51-29](https://user-images.githubusercontent.com/84619862/132708224-d1f0d69f-8b91-4050-a098-0038225c8a66.png)

Before, i tried the mpiexe I've run the simulation without this option enabled and it went smoothly.

I've realized that this error is related with the missing of the librabry libmpi.so.20. However since i'm using Ubuntu 20.04 LTS this librabry was updated to libmpi.so.40 i think (this one is installed in my pc). I wonder if anyone knows how to solve this problem?

**Desktop Information**

 - OS: [Ubuntu 20.04 LTS
 - SimVascular Version 2021.06.15
 - Medical Image Filetype [e.g. DICOM, MHA, ...]

Thank you in advance for your help. Best reagrds,
André.

**Comment by ktbolt** [comment]
@andre-mourato-61459 Please post this issue on the SV Forum.
