### ISSUE TITLE
Integrate scikit-image image processing tools

### ISSUE THREAD

**Issue by aabrown100-git** [SimVascular/SimVascular#949]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The Image Processing tool available in SimVascular is somewhat limited. I am working with relatively poor quality light-sheet images, and am interested in applying more advanced image processing techniques. For example, I have explored performing adaptive histogram equalization, which is not available in SimVascular but is available in ImageJ and scikit-image.

**Describe alternatives you've considered**
scikit-image is easily accessible through Python scripting, but it would be great if it were integrated into SimVascular for a quicker workflow.

**Additional context**
scikit-image (https://scikit-image.org/) appears to be a well-regarded and well-maintained image processing toolkit for Python.

**Comment by ktbolt** [comment]
@aabrown100-git We try not to add new software components to SV unless there is a really good reason to do so, the SV software dependencies are already quite large complex. 

The Insight Toolkit (**ITK**) is already integrated into SV although it is currently accessible only from C++.  Note that SV does not have integrated image filtering operations. The  Image Processing tool  is part of MITK and is not integrated with SV.

**Comment by ktbolt** [comment]
No response from @aabrown100-git so closing this.
