### ISSUE TITLE
Add face combining to SV Python

### ISSUE THREAD

**Issue by zasexton** [SimVascular/SimVascular#960]
**Is your feature request related to a problem? Please describe.**
Exposing face combining utilities for SV python so that polydata modelfaceids can be combined into one face. 

**Describe the solution you'd like**
Ideally under the mesh_utils module for SV python a function 

combine_faces(model,target,loss)

which takes as input the model polydata object as well as a target face id (integer) to combine into and a second face id (integer)
which will lose its original face id and take the target face id. 

**Describe alternatives you've considered**
I've implemented my own version here https://github.com/SimVascular/SimVascular/issues/867#issuecomment-849791357 I am not sure how robust it is although I have not yet had problems with it. Mainly having this functionality included in the main SV repository will help ensure that this feature is not lost in my specific fork.

**Additional context**

**Comment by zasexton** [comment]
@ktbolt Thank you! I haven't noticed any issues with face combining on my cases so far!

**Comment by ktbolt** [comment]
Very good! I will close this for now, reopen it if you encounter any problems.
