### ISSUE TITLE
Fix the  ROM Simulation Preferences panel

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/SimVascular#983]
The ROM Simulation Preferences panel has two issues

1) The panel was copied from the SImulations panel and contains no GUI controls related to the 1D solver
2) The ROM Simulation plugin does not use values from the ROM Simulations panel

<img width="1012" alt="Screen Shot 2022-07-13 at 6 47 16 PM" src="https://user-images.githubusercontent.com/23109458/178879900-1972c388-15b9-4e6b-948a-433507898145.png">

This not really a problem on MacOS and Ubuntu where the default /usr/local/sv/oneDSolver is used to find the 1D solver. However, on Windows the 1D solver can't be found.

**Comment by ktbolt** [comment]
I've fixed the Preferences panel and added code to process the values set there. A default value is set to the latest installed 1D solver.

<img width="1012" alt="Screen Shot 2022-07-14 at 2 40 50 PM" src="https://user-images.githubusercontent.com/23109458/179091144-b763e16e-92fd-4b25-9b56-1d359122efe0.png">

This works on MacOS and Ubuntu.

**Comment by ktbolt** [comment]
This now works on Windows so users can now run the 1D solver on Windows!

Merged into master.

**Comment by zasexton** [comment]
Say it ain't so!!

**Comment by ktbolt** [comment]
@zasexton There is a chance that it might actually be so!
