### ISSUE TITLE
is it possible to run simVascular in command line Mode?

### ISSUE THREAD

**Issue by jiazeyu1987** [SimVascular/SimVascular#996]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ktbolt** [comment]
@jiazeyu1987 This question should be posted in the SV Forum https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=188&pluginname=phpBB so other users can see it.
