### ISSUE TITLE
Import volumetric mesh on SimVascular (?)

### ISSUE THREAD

**Issue by Angelo21IngBio** [SimVascular/SimVascular#998]
Hi everyone, I wanted to ask you if it was possible to import volumetric meshes on SimVascular, for example in (.vtu) format.
So far I have understood that it is possible to import only surface models in the SV Modeling module.
Thanks everyone in advance for your interest.

**Comment by ktbolt** [comment]
@Angelo21IngBio Please post this question in the SV Forum so other users can see it. Thanks!
